import { CaseActionStatus, DataClassification } from "@prisma/client";
import { db } from "@/lib/db";
import { can, forbidden } from "@/lib/authorization";
import { appendAudit } from "@/lib/audit";
import { getCaseWallCase } from "@/lib/case-wall";
import { getRequestContext, unauthorized } from "@/lib/request-context";

export async function GET(request:Request,{params}:{params:Promise<{id:string}>}){const ctx=getRequestContext(request);if(!ctx)return unauthorized();if(!can(ctx,"cases:read"))return forbidden();const {id}=await params;if(!await getCaseWallCase(ctx,id))return forbidden("Case wall denies access to this matter.");return Response.json({data:await db.caseAction.findMany({where:{tenantId:ctx.tenantId,caseId:id},orderBy:[{dueAt:"asc"},{createdAt:"desc"}]})})}
export async function POST(request:Request,{params}:{params:Promise<{id:string}>}){const ctx=getRequestContext(request);if(!ctx)return unauthorized();if(!can(ctx,"cases:write"))return forbidden();const {id}=await params;if(!await getCaseWallCase(ctx,id))return forbidden("Case wall denies access to this matter.");const body=await request.json() as {actionType?:string;description?:string;ownerId?:string;dueAt?:string;subjectEmploymentId?:string};const actionType=body.actionType?.trim(),description=body.description?.trim(),ownerId=body.ownerId?.trim();if(!actionType||!description||!ownerId)return Response.json({error:"actionType, description and ownerId are required."},{status:400});const data=await db.$transaction(async tx=>{const action=await tx.caseAction.create({data:{tenantId:ctx.tenantId,caseId:id,subjectEmploymentId:body.subjectEmploymentId,actionType,description,ownerId,dueAt:body.dueAt?new Date(body.dueAt):undefined,status:CaseActionStatus.OPEN}});await appendAudit(tx,ctx,{action:"employee-case.corrective-action-created",resourceType:"CaseAction",resourceId:action.id,classification:DataClassification.HIGHLY_RESTRICTED});return action});return Response.json({data},{status:201})}
