"use client";
import{useEffect,useRef,useState}from"react";import{Check,Play,X}from"lucide-react";import{useLocale}from"@/components/locale-provider";import{acknowledgeCompensationNotification,compensationActionMessage,submitCompensationAction,type CompensationActionResult,type CompensationDecision}from"@/lib/compensation-client-action";
export type CompensationAttemptRegistry=Map<string,CompensationActionResult>;
export function CompensationActionButtons({changeId,allowedActions,attemptRegistry,disabled=false}:{changeId:string;allowedActions:readonly CompensationDecision[];attemptRegistry?:CompensationAttemptRegistry;disabled?:boolean}){
 const{locale}=useLocale();const[busy,setBusy]=useState<CompensationDecision|null>(null),[result,setResult]=useState<CompensationActionResult|null>(attemptRegistry?.get(changeId)??null);const lock=useRef(false),mounted=useRef(true),controller=useRef<AbortController|null>(null);
 useEffect(()=>()=>{mounted.current=false;controller.current?.abort();},[]);
 async function run(decision:CompensationDecision){if(disabled||lock.current||attemptRegistry?.has(changeId)||!allowedActions.includes(decision))return;if(!window.confirm(locale==="tr"?"Bu kısıtlı ücret işlemi kayda alınsın mı?":"Record this restricted compensation action?"))return;lock.current=true;attemptRegistry?.set(changeId,{outcome:"unknown"});setBusy(decision);controller.current=new AbortController();let outcome:CompensationActionResult;try{outcome=await submitCompensationAction({kind:"decision",changeId,decision},{signal:controller.current.signal});}catch{outcome={outcome:"unknown"};}if(!mounted.current)return;attemptRegistry?.set(changeId,outcome);setResult(outcome);setBusy(null);if(outcome.outcome==="saved"){void acknowledgeCompensationNotification(changeId).catch(()=>{});window.dispatchEvent(new Event("hrbp:lifecycle-actions-changed"));window.dispatchEvent(new Event("hrbp:notifications-changed"));}}
 if(result)return <div style={{display:"grid",gap:5,maxWidth:270}}><small role={result.outcome==="saved"?"status":"alert"}>{compensationActionMessage(result,locale)}</small><button className="secondary-button" type="button" onClick={()=>window.location.reload()}>{locale==="tr"?"Yenile ve kontrol et":"Reload and review"}</button></div>;
 return <div style={{display:"flex",gap:6,flexWrap:"wrap"}}>{allowedActions.includes("APPROVE")?<button className="secondary-button" type="button" disabled={disabled||busy!==null} onClick={()=>void run("APPROVE")}><Check size={13}/>{busy==="APPROVE"?"…":locale==="tr"?"Onayla":"Approve"}</button>:null}{allowedActions.includes("REJECT")?<button className="secondary-button" type="button" disabled={disabled||busy!==null} onClick={()=>void run("REJECT")}><X size={13}/>{busy==="REJECT"?"…":locale==="tr"?"Reddet":"Reject"}</button>:null}{allowedActions.includes("APPLY")?<button className="secondary-button" type="button" disabled={disabled||busy!==null} onClick={()=>void run("APPLY")}><Play size={13}/>{busy==="APPLY"?"…":locale==="tr"?"Uygula":"Apply"}</button>:null}</div>;
}