"use client";

import { useMemo, useState } from "react";
import { Archive, BadgeCheck, BriefcaseBusiness, Building2, ChevronRight, CircleAlert, Clock3, Download, FileKey2, FileText, Fingerprint, History, KeyRound, LockKeyhole, MoreHorizontal, Network, Search, ShieldCheck, UserCheck, UsersRound } from "lucide-react";
import { auditEvents, documents, employees, orgUnits, positions } from "@/lib/demo-data";

function Stat({ label, value, meta, icon: Icon }: { label:string; value:string; meta:string; icon: React.ComponentType<{size?:number}> }) {
  return <div className="enterprise-stat"><div className="enterprise-stat-icon"><Icon size={17}/></div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>;
}

function Toolbar({ query, setQuery, placeholder }: { query:string; setQuery:(v:string)=>void; placeholder:string }) {
  return <div className="enterprise-toolbar"><div className="enterprise-search"><Search size={16}/><input value={query} onChange={(e)=>setQuery(e.target.value)} placeholder={placeholder}/></div><button className="secondary-button"><Download size={15}/> Export</button></div>;
}

export function CoreHRWorkspace({ slug }: { slug:string }) {
  const [query, setQuery] = useState("");
  const filteredPeople = useMemo(() => employees.filter((p)=>[p.name,p.role,p.department,p.id].join(" ").toLowerCase().includes(query.toLowerCase())), [query]);

  if (slug === "people") return <>
    <div className="enterprise-stats"><Stat label="Active workers" value="512" meta="+18 this quarter" icon={UsersRound}/><Stat label="Preboarding" value="8" meta="Next 30 days" icon={UserCheck}/><Stat label="On leave" value="14" meta="2 long-term" icon={Clock3}/><Stat label="Data quality" value="98.6%" meta="7 records need review" icon={BadgeCheck}/></div>
    <Toolbar query={query} setQuery={setQuery} placeholder="Search name, employee ID, role or department…"/>
    <div className="card enterprise-table-card"><div className="table-title"><div><h3>People directory</h3><p>Golden employee records with current effective-dated assignment.</p></div><span>{filteredPeople.length} shown</span></div><div className="table-wrap"><table className="enterprise-table"><thead><tr><th>Employee</th><th>Position</th><th>Department</th><th>Location</th><th>Status</th><th>Start date</th><th/></tr></thead><tbody>{filteredPeople.map((p)=><tr key={p.id}><td><div className="enterprise-person"><span>{p.initials}</span><div><strong>{p.name}</strong><small>{p.id}</small></div></div></td><td><strong className="cell-strong">{p.role}</strong><small className="cell-sub">{p.position}</small></td><td>{p.department}</td><td>{p.location}</td><td><em className={`pill ${p.status.toLowerCase()}`}>{p.status}</em></td><td>{p.start}</td><td><button className="row-action"><ChevronRight size={15}/></button></td></tr>)}</tbody></table></div></div>
  </>;

  if (slug === "organization") return <>
    <div className="enterprise-stats"><Stat label="Legal entities" value="4" meta="3 operating countries" icon={Building2}/><Stat label="Organization units" value="42" meta="6 levels" icon={Network}/><Stat label="Managers" value="71" meta="7.2 avg span" icon={UsersRound}/><Stat label="Orphan positions" value="0" meta="Hierarchy healthy" icon={ShieldCheck}/></div>
    <div className="org-layout"><div className="card org-tree"><div className="table-title"><div><h3>Organization model</h3><p>Effective 21 Sep 2026 · approved hierarchy</p></div><button className="secondary-button">Scenario view</button></div><div className="org-nodes">{orgUnits.map((o,i)=><div className={`org-node level-${Math.min(i,2)}`} key={o.code}><div className="org-node-icon"><Building2 size={16}/></div><div><strong>{o.name}</strong><small>{o.type} · {o.code}</small></div><div className="org-node-count"><strong>{o.people}</strong><small>people</small></div></div>)}</div></div><div className="card org-insight"><div className="table-title"><div><h3>Structure health</h3><p>Governed organization signals</p></div></div><div className="health-list"><div><span>Manager span within policy</span><strong>88%</strong></div><div><span>Positions with valid owner</span><strong>100%</strong></div><div><span>Cost centers mapped</span><strong>96%</strong></div><div><span>Upcoming reorganizations</span><strong>2</strong></div></div><div className="governance-note"><ShieldCheck size={17}/><p>Organization changes preserve historical truth. Approved changes create a new effective-dated version instead of overwriting the previous assignment.</p></div></div></div>
  </>;

  if (slug === "positions") return <>
    <div className="enterprise-stats"><Stat label="Positions" value="548" meta="512 filled" icon={BriefcaseBusiness}/><Stat label="Open" value="21" meta="12 recruiting" icon={CircleAlert}/><Stat label="Planned" value="15" meta="FY27 plan" icon={Clock3}/><Stat label="Critical roles" value="37" meta="28 with successor" icon={ShieldCheck}/></div>
    <div className="card enterprise-table-card"><div className="table-title"><div><h3>Position register</h3><p>Budgeted seats exist independently from their incumbents.</p></div><button className="secondary-button">Position controls</button></div><div className="table-wrap"><table className="enterprise-table"><thead><tr><th>Position</th><th>Organization</th><th>Grade</th><th>Location</th><th>Incumbent</th><th>Status</th><th>Critical</th></tr></thead><tbody>{positions.map((p)=><tr key={p.code}><td><strong className="cell-strong">{p.title}</strong><small className="cell-sub">{p.code}</small></td><td>{p.org}</td><td>{p.grade}</td><td>{p.location}</td><td>{p.incumbent}</td><td><em className={`pill ${p.status.toLowerCase()}`}>{p.status}</em></td><td>{p.critical ? <span className="critical-badge"><ShieldCheck size={13}/> Yes</span> : "—"}</td></tr>)}</tbody></table></div></div>
  </>;

  if (slug === "employee-360") {
    const p = employees[0];
    return <><div className="employee-hero card"><div className="employee-avatar">{p.initials}</div><div className="employee-identity"><div className="identity-top"><h2>{p.name}</h2><em className="pill active">Active</em></div><p>{p.role} · {p.department}</p><div className="identity-meta"><span>{p.id}</span><span>{p.position}</span><span>{p.location}</span><span>Manager: {p.manager}</span></div></div><button className="secondary-button"><MoreHorizontal size={16}/> Actions</button></div><div className="profile-tabs"><button className="active">Overview</button><button>Employment</button><button>Compensation</button><button>Performance</button><button>Talent</button><button>Documents</button><button>History</button></div><div className="profile-grid"><div className="card profile-card"><div className="table-title"><div><h3>Employment</h3><p>Current effective record</p></div></div><dl><div><dt>Position</dt><dd>{p.role}</dd></div><div><dt>Department</dt><dd>{p.department}</dd></div><div><dt>Location</dt><dd>{p.location}</dd></div><div><dt>Start date</dt><dd>{p.start}</dd></div><div><dt>Worker type</dt><dd>Regular employee</dd></div><div><dt>FTE</dt><dd>1.00</dd></div></dl></div><div className="card profile-card"><div className="table-title"><div><h3>Lifecycle</h3><p>Immutable business history</p></div></div><div className="profile-timeline"><div><i/><span><strong>Promotion</strong><small>Engineering Director · 01 Jan 2026</small></span></div><div><i/><span><strong>Manager changed</strong><small>Mert Demir · 01 Aug 2025</small></span></div><div><i/><span><strong>Compensation changed</strong><small>Annual review · 01 Jan 2025</small></span></div><div><i/><span><strong>Hired</strong><small>12 Mar 2021</small></span></div></div></div><div className="card profile-card security-card"><div className="table-title"><div><h3>Data access</h3><p>Classification & policy context</p></div></div><div className="security-status"><LockKeyhole size={20}/><div><strong>Confidential</strong><small>Standard HR record policy</small></div></div><div className="mini-policy"><span>Salary</span><strong>Restricted</strong></div><div className="mini-policy"><span>ER cases</span><strong>Case wall</strong></div><div className="mini-policy"><span>Audit logging</span><strong>Enabled</strong></div></div></div></>;
  }

  if (slug === "documents") return <><div className="enterprise-stats"><Stat label="Vault objects" value="4,218" meta="100% encrypted" icon={FileText}/><Stat label="Restricted" value="1,842" meta="Policy controlled" icon={LockKeyhole}/><Stat label="Expiring soon" value="17" meta="Next 30 days" icon={Clock3}/><Stat label="Legal hold" value="6" meta="Deletion blocked" icon={Archive}/></div><div className="card enterprise-table-card"><div className="table-title"><div><h3>Employee document vault</h3><p>Private objects, classification-aware access and retention metadata.</p></div><button className="secondary-button"><KeyRound size={15}/> Vault controls</button></div><div className="table-wrap"><table className="enterprise-table"><thead><tr><th>Document</th><th>Owner</th><th>Category</th><th>Classification</th><th>Retention</th><th>Updated</th></tr></thead><tbody>{documents.map((d)=><tr key={d.name}><td><span className="document-name"><FileText size={15}/><strong>{d.name}</strong></span></td><td>{d.owner}</td><td>{d.category}</td><td><em className={`classification ${d.classification.toLowerCase()}`}>{d.classification}</em></td><td>{d.retention}</td><td>{d.updated}</td></tr>)}</tbody></table></div></div></>;

  if (slug === "privacy") return <><div className="enterprise-stats"><Stat label="Processing activities" value="38" meta="36 approved" icon={FileKey2}/><Stat label="Open DSRs" value="4" meta="All within SLA" icon={Fingerprint}/><Stat label="Retention rules" value="24" meta="3 country overrides" icon={History}/><Stat label="High-risk domains" value="5" meta="DPIA governed" icon={ShieldCheck}/></div><div className="privacy-grid"><div className="card"><div className="table-title"><div><h3>Processing register</h3><p>Purpose, legal basis, classification and retention by domain.</p></div></div><div className="processing-list">{[["Employee administration","Contract / legal obligation","Confidential","Employment + statutory"],["Payroll","Legal obligation","Restricted","Country policy"],["Employee relations","Legitimate/legal obligations","Highly restricted","Case policy"],["Talent & succession","Legitimate interest","Confidential","Active + configured"]].map((r)=><div key={r[0]}><strong>{r[0]}</strong><span>{r[1]}</span><em>{r[2]}</em><small>{r[3]}</small></div>)}</div></div><div className="card privacy-controls"><div className="table-title"><div><h3>Privacy controls</h3><p>Tenant posture</p></div></div><div className="control-score"><span>96</span><small>/100</small></div><ul><li><BadgeCheck size={15}/> Purpose metadata enforced</li><li><BadgeCheck size={15}/> Restricted admin separation</li><li><BadgeCheck size={15}/> Retention evaluation active</li><li><BadgeCheck size={15}/> DSR workflow enabled</li><li><CircleAlert size={15}/> 2 records missing country basis</li></ul></div></div></>;

  if (slug === "audit") return <><div className="enterprise-stats"><Stat label="Events today" value="18,492" meta="Append-only" icon={History}/><Stat label="Privileged reads" value="142" meta="Purpose captured" icon={KeyRound}/><Stat label="Policy denials" value="23" meta="No bypass" icon={ShieldCheck}/><Stat label="Ledger integrity" value="100%" meta="Hash chain verified" icon={BadgeCheck}/></div><div className="card enterprise-table-card"><div className="table-title"><div><h3>Audit ledger</h3><p>Security-relevant reads and all mutations across the tenant.</p></div><button className="secondary-button">Verify chain</button></div><div className="table-wrap"><table className="enterprise-table"><thead><tr><th>Actor</th><th>Action</th><th>Resource</th><th>Declared purpose</th><th>Classification</th><th>Time</th></tr></thead><tbody>{auditEvents.map((a,i)=><tr key={i}><td><strong className="cell-strong">{a.actor}</strong></td><td>{a.action}</td><td><code>{a.resource}</code></td><td>{a.purpose}</td><td><em className={`classification ${a.classification.toLowerCase()}`}>{a.classification}</em></td><td>{a.time}</td></tr>)}</tbody></table></div></div></>;

  return null;
}

export const coreWorkspaceSlugs = new Set(["people","organization","positions","employee-360","documents","privacy","audit"]);
