import { AlertTriangle, BadgeCheck, BookOpenCheck, CheckCircle2, CircleHelp, Clock3, FileLock2, Gavel, GitBranch, LockKeyhole, MoreHorizontal, Route, ShieldCheck, Sparkles, TimerReset, UsersRound, Workflow } from "lucide-react";
import { getServerLocale } from "@/lib/i18n-server";
import type { Locale } from "@/lib/i18n";

export const employeeServicesWorkspaceSlugs = new Set(["employee-relations", "hr-service", "policies", "workflows"]);

const erRows = [["ER-2026-0041","Conduct","Case team only","Investigation","11d","Open"],["ER-2026-0037","Grievance","Case team only","Findings","18d","Action required"],["ER-2026-0032","Conflict","Case team only","Appeal","29d","Review"],["ER-2026-0028","Policy breach","Case team only","Closure","35d","Resolved"]];
const serviceRows = [["HR-2026-1842","Employment letter","42m","2h 18m","HR Operations","In progress"],["HR-2026-1839","Payroll query","1h 14m","46m","Payroll","Waiting employee"],["HR-2026-1837","Benefits","2h 02m","5h 58m","Total Rewards","In progress"],["HR-2026-1828","Policy question","4h 31m","19h 29m","HRBP","Open"]];
const policyRows = [["POL-HR-001","Code of Conduct","v4.2","All employees","99.1%","Dec 2026","Published"],["POL-HR-006","Remote Work","v3.1","Eligible employees","96.8%","Nov 2026","Published"],["POL-SEC-004","Acceptable Use","v5.0","All workforce","98.4%","Jan 2027","Published"],["POL-HR-011","Disciplinary Process","v2.4","Managers & HR","94.2%","Oct 2026","Review"]];
const workflowRows = [["New hire orchestration","Offer accepted","84","0","HR Operations","Active"],["Job change","Employment event","31","1","HRBP","Active"],["Leave approval","Request submitted","126","0","HR Operations","Active"],["Policy attestation","Policy published","512","3","Compliance","Active"]];

function c(locale: Locale, en: string, tr: string) { return locale === "tr" ? tr : en; }
function v(locale: Locale, value: string) {
  if (locale !== "tr") return value;
  const map: Record<string,string> = {
    Conduct:"Davranış", Grievance:"Şikâyet", Conflict:"Çatışma", "Policy breach":"Politika ihlali", "Case team only":"Yalnızca vaka ekibi", Investigation:"Soruşturma", Findings:"Bulgular", Appeal:"İtiraz", Closure:"Kapanış", Open:"Açık", "Action required":"Aksiyon gerekli", Review:"İncele", Resolved:"Çözüldü",
    "Employment letter":"Çalışma belgesi", "Payroll query":"Bordro talebi", Benefits:"Yan haklar", "Policy question":"Politika sorusu", "HR Operations":"İK Operasyon", Payroll:"Bordro", "Total Rewards":"Toplam Ödüllendirme", "In progress":"Devam ediyor", "Waiting employee":"Çalışan bekleniyor",
    "Code of Conduct":"Davranış Kuralları", "Remote Work":"Uzaktan Çalışma", "Acceptable Use":"Kabul Edilebilir Kullanım", "Disciplinary Process":"Disiplin Süreci", "All employees":"Tüm çalışanlar", "Eligible employees":"Uygun çalışanlar", "All workforce":"Tüm iş gücü", "Managers & HR":"Yöneticiler & İK", Published:"Yayınlandı",
    "New hire orchestration":"Yeni işe alım orkestrasyonu", "Offer accepted":"Teklif kabul edildi", "Job change":"İş değişikliği", "Employment event":"İstihdam olayı", "Leave approval":"İzin onayı", "Request submitted":"Talep gönderildi", "Policy attestation":"Politika onayı", "Policy published":"Politika yayınlandı", Compliance:"Uyum", Active:"Aktif"
  };
  return map[value] ?? value;
}
function Metric({ icon, label, value, meta }: { icon: React.ReactNode; label: string; value: string; meta: string }) { return <div className="services-metric card"><div className="services-metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>; }
function Pill({ value, locale }: { value: string; locale: Locale }) { const key = value.toLowerCase().replace(/\s+/g,"-"); return <em className={`services-pill ${key}`}>{v(locale,value)}</em>; }

function EmployeeRelationsWorkspace({ locale }: { locale: Locale }) { return <><section className="services-metrics"><Metric icon={<FileLock2 size={18}/>} label={c(locale,"Open restricted cases","Açık kısıtlı vakalar")} value="14" meta={c(locale,"Case-wall protected matters","Vaka duvarıyla korunan kayıtlar")}/><Metric icon={<TimerReset size={18}/>} label={c(locale,"Triage due","Triyaj süresi yaklaşan")} value="3" meta={c(locale,"Within next 24 hours","Önümüzdeki 24 saat içinde")}/><Metric icon={<Gavel size={18}/>} label={c(locale,"Findings pending","Bekleyen bulgular")} value="5" meta={c(locale,"2 legal reviews requested","2 hukuk incelemesi istendi")}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Appeals","İtirazlar")} value="2" meta={c(locale,"Independent reviewer required","Bağımsız inceleyici gerekli")}/></section><section className="services-split"><div className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Restricted casework","Kısıtlı vaka yönetimi")}</span><h3>{c(locale,"Employee relations case register","Çalışan ilişkileri vaka envanteri")}</h3></div><button><MoreHorizontal size={18}/></button></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Case","Vaka")}</th><th>{c(locale,"Type","Tür")}</th><th>{c(locale,"Access","Erişim")}</th><th>{c(locale,"Phase","Aşama")}</th><th>{c(locale,"Age","Yaş")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{erRows.map((r)=><tr key={r[0]}>{r.slice(0,5).map((x,i)=><td key={i}>{v(locale,x)}</td>)}<td><Pill value={r[5]} locale={locale}/></td></tr>)}</tbody></table></div></div><aside className="card services-side restricted-case"><div className="services-panel-head"><div><span className="section-kicker">Case Wall</span><h3>{c(locale,"Need-to-know boundary","Bilmesi gereken prensibi")}</h3></div><LockKeyhole size={18}/></div><div className="services-control-stack"><div><ShieldCheck size={17}/><span><strong>{c(locale,"Membership enforced","Üyelik zorunlu")}</strong><small>{c(locale,"Tenant administration does not grant access to ER matters.","Tenant yöneticiliği çalışan ilişkileri vakalarına erişim sağlamaz.")}</small></span></div><div><FileLock2 size={17}/><span><strong>{c(locale,"Highly restricted evidence","Yüksek kısıtlı kanıt")}</strong><small>{c(locale,"Allegations, interviews, findings and appeals stay inside the case wall.","İddialar, görüşmeler, bulgular ve itirazlar vaka duvarı içinde kalır.")}</small></span></div><div><BadgeCheck size={17}/><span><strong>{c(locale,"Read access is auditable","Okuma erişimi denetlenebilir")}</strong><small>{c(locale,"Purpose and actor context travel with sensitive case activity.","Amaç ve aktör bağlamı hassas vaka aktiviteleriyle birlikte kaydedilir.")}</small></span></div></div></aside></section></>; }

function HRServiceWorkspace({ locale }: { locale: Locale }) { return <><section className="services-metrics"><Metric icon={<CircleHelp size={18}/>} label={c(locale,"Open requests","Açık talepler")} value="47" meta={c(locale,"Across 8 service queues","8 hizmet kuyruğunda")}/><Metric icon={<Clock3 size={18}/>} label={c(locale,"SLA compliance","SLA uyumu")} value="97.4%" meta={c(locale,"Rolling 30 days","Son 30 gün")}/><Metric icon={<UsersRound size={18}/>} label={c(locale,"First response","İlk yanıt")} value="38m" meta={c(locale,"Median response time","Medyan yanıt süresi")}/><Metric icon={<Sparkles size={18}/>} label={c(locale,"Auto-routed","Otomatik yönlendirilen")} value="82%" meta={c(locale,"Rules route before human triage","Kurallar insan triyajından önce yönlendirir")}/></section><section className="services-split"><div className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Employee service","Çalışan hizmetleri")}</span><h3>{c(locale,"Request operating queue","Talep operasyon kuyruğu")}</h3></div><button><MoreHorizontal size={18}/></button></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Request","Talep")}</th><th>{c(locale,"Category","Kategori")}</th><th>{c(locale,"Age","Yaş")}</th><th>{c(locale,"SLA left","Kalan SLA")}</th><th>{c(locale,"Queue","Kuyruk")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{serviceRows.map((r)=><tr key={r[0]}>{r.slice(0,5).map((x,i)=><td key={i}>{v(locale,x)}</td>)}<td><Pill value={r[5]} locale={locale}/></td></tr>)}</tbody></table></div></div><aside className="card services-side"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Routing","Yönlendirme")}</span><h3>{c(locale,"Service governance","Hizmet yönetişimi")}</h3></div><Route size={18}/></div><div className="services-control-stack"><div><CheckCircle2 size={17}/><span><strong>{c(locale,"Identity-bound self service","Kimliğe bağlı self servis")}</strong><small>{c(locale,"Employee submissions use trusted employment context, not a user-entered person ID.","Çalışan talepleri kullanıcı tarafından girilen kişi ID'si yerine güvenilir istihdam bağlamını kullanır.")}</small></span></div><div><TimerReset size={17}/><span><strong>{c(locale,"Priority-aware SLA","Öncelik duyarlı SLA")}</strong><small>{c(locale,"Critical requests receive a four-hour service target.","Kritik talepler dört saatlik hizmet hedefi alır.")}</small></span></div><div><ShieldCheck size={17}/><span><strong>{c(locale,"Private HR notes","Özel İK notları")}</strong><small>{c(locale,"Requestor-visible replies stay separated from internal case handling.","Talep sahibinin görebildiği yanıtlar iç vaka notlarından ayrı tutulur.")}</small></span></div></div></aside></section></>; }

function PoliciesWorkspace({ locale }: { locale: Locale }) { return <><section className="services-metrics"><Metric icon={<BookOpenCheck size={18}/>} label={c(locale,"Published policies","Yayınlanan politikalar")} value="34" meta={c(locale,"7 jurisdiction-specific variants","7 ülke/bölge özel varyant")}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Review due","İnceleme tarihi yaklaşan")} value="4" meta={c(locale,"Within next 60 days","Önümüzdeki 60 gün içinde")}/><Metric icon={<BadgeCheck size={18}/>} label={c(locale,"Acknowledgement","Onaylama oranı")} value="97.6%" meta={c(locale,"Current published versions","Güncel yayınlanmış sürümler")}/><Metric icon={<ShieldCheck size={18}/>} label={c(locale,"Active exceptions","Aktif istisnalar")} value="11" meta={c(locale,"All with expiry or review date","Tümünde bitiş veya inceleme tarihi var")}/></section><section className="services-split"><div className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Policy lifecycle","Politika yaşam döngüsü")}</span><h3>{c(locale,"Controlled policy register","Kontrollü politika envanteri")}</h3></div><button><MoreHorizontal size={18}/></button></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Code","Kod")}</th><th>{c(locale,"Policy","Politika")}</th><th>{c(locale,"Version","Sürüm")}</th><th>{c(locale,"Audience","Hedef kitle")}</th><th>{c(locale,"Acknowledged","Onaylandı")}</th><th>{c(locale,"Review","İnceleme")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{policyRows.map((r)=><tr key={r[0]}>{r.slice(0,6).map((x,i)=><td key={i}>{v(locale,x)}</td>)}<td><Pill value={r[6]} locale={locale}/></td></tr>)}</tbody></table></div></div><aside className="card services-side"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Control evidence","Kontrol kanıtı")}</span><h3>{c(locale,"Policy integrity","Politika bütünlüğü")}</h3></div></div><div className="services-control-stack"><div><BadgeCheck size={17}/><span><strong>{c(locale,"Version-bound acknowledgement","Sürüme bağlı onay")}</strong><small>{c(locale,"Acknowledgements bind employee, exact version, actor and timestamp.","Onay kayıtları çalışanı, tam sürümü, aktörü ve zaman damgasını bağlar.")}</small></span></div><div><ShieldCheck size={17}/><span><strong>{c(locale,"Content hashing","İçerik hashleme")}</strong><small>{c(locale,"Published text can be integrity-checked against its stored SHA-256 hash.","Yayınlanan metin saklanan SHA-256 özetiyle bütünlük kontrolünden geçirilebilir.")}</small></span></div><div><Clock3 size={17}/><span><strong>{c(locale,"Review & exception dates","İnceleme & istisna tarihleri")}</strong><small>{c(locale,"Policy debt becomes visible before controls silently expire.","Kontroller sessizce süresi dolmadan politika borcu görünür hale gelir.")}</small></span></div></div></aside></section></>; }

function WorkflowsWorkspace({ locale }: { locale: Locale }) { return <><section className="services-metrics"><Metric icon={<Workflow size={18}/>} label={c(locale,"Active definitions","Aktif tanımlar")} value="18" meta={c(locale,"Versioned process templates","Sürümlenmiş süreç şablonları")}/><Metric icon={<GitBranch size={18}/>} label={c(locale,"In flight","Devam eden")} value="263" meta={c(locale,"Across employee lifecycle events","Çalışan yaşam döngüsü olaylarında")}/><Metric icon={<Clock3 size={18}/>} label={c(locale,"Waiting approvals","Onay bekleyen") } value="31" meta={c(locale,"9 due within 8 hours","9 kayıt 8 saat içinde doluyor")}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Failed tasks","Başarısız görevler")} value="4" meta={c(locale,"No silent workflow failure","Sessiz iş akışı hatası yok")}/></section><section className="services-split"><div className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Process orchestration","Süreç orkestrasyonu")}</span><h3>{c(locale,"Workflow control plane","İş akışı kontrol düzlemi")}</h3></div><button><MoreHorizontal size={18}/></button></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Workflow","İş akışı")}</th><th>{c(locale,"Trigger","Tetikleyici")}</th><th>{c(locale,"Instances","Örnekler")}</th><th>{c(locale,"Failures","Hatalar")}</th><th>{c(locale,"Owner","Sahip")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{workflowRows.map((r)=><tr key={r[0]}>{r.slice(0,5).map((x,i)=><td key={i}>{v(locale,x)}</td>)}<td><Pill value={r[5]} locale={locale}/></td></tr>)}</tbody></table></div></div><aside className="card services-side workflow-side"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Orchestration pattern","Orkestrasyon modeli")}</span><h3>{c(locale,"Event → decision → action","Olay → karar → aksiyon")}</h3></div></div><div className="workflow-chain"><span>{c(locale,"Event","Olay")}</span><i>→</i><span>{c(locale,"Rules","Kurallar")}</span><i>→</i><span>{c(locale,"Approval","Onay")}</span><i>→</i><span>{c(locale,"Task","Görev")}</span><i>→</i><span>{c(locale,"Audit","Denetim")}</span></div><p>{c(locale,"Definitions are versioned. Every instance keeps its subject, actor, task state, SLA and event history instead of hiding process logic inside email threads.","Tanımlar sürümlenir. Her örnek süreç mantığını e-posta zincirlerinde saklamak yerine konu, aktör, görev durumu, SLA ve olay geçmişini korur.")}</p></aside></section></>; }

export async function EmployeeServicesWorkspace({ slug }: { slug: string }) { const locale = await getServerLocale(); return <div className="services-shell">{slug === "employee-relations" ? <EmployeeRelationsWorkspace locale={locale}/> : slug === "hr-service" ? <HRServiceWorkspace locale={locale}/> : slug === "policies" ? <PoliciesWorkspace locale={locale}/> : <WorkflowsWorkspace locale={locale}/>}</div>; }
