import { AlertTriangle, BadgeCheck, BookOpenCheck, CheckCircle2, CircleHelp, Clock3, FileLock2, Gavel, GitBranch, LockKeyhole, Route, ShieldCheck, TimerReset, UsersRound, Workflow } from "lucide-react";
import { can, type Capability } from "@/lib/authorization";
import { getServerRequestContext } from "@/lib/server-session";
import { getServerLocale } from "@/lib/i18n-server";
import type { Locale } from "@/lib/i18n";
import { getEmployeeRelationsLiveData, getHRServiceLiveData, getPoliciesLiveData, getWorkflowsLiveData } from "@/lib/employee-services-live-data";
import { EmployeeServicesWorkspace } from "@/components/employee-services-workspace";
import { PolicyReviewActions } from "@/components/policy-review-actions";

function c(locale:Locale,en:string,tr:string){return locale==="tr"?tr:en}
function sv(locale:Locale,value:string){if(locale!=="tr")return value;const m:Record<string,string>={Open:"Açık",Closed:"Kapalı",Pending:"Bekliyor",Approved:"Onaylandı",Active:"Aktif",Published:"Yayınlandı",Review:"İncelemede",Draft:"Taslak","In progress":"Devam ediyor","Waiting employee":"Çalışan bekleniyor","Waiting third party":"Üçüncü taraf bekleniyor",Resolved:"Çözüldü","Action required":"Aksiyon gerekli",Restricted:"Kısıtlı",Confidential:"Gizli"};return m[value]??value}
function Metric({icon,label,value,meta}:{icon:React.ReactNode;label:string;value:string;meta:string}){return <div className="services-metric card"><div className="services-metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function Pill({value,locale}:{value:string;locale:Locale}){return <em className={`services-pill ${value.toLowerCase().replace(/\s+/g,"-")}`}>{sv(locale,value)}</em>}
function Empty({text,columns=8}:{text:string;columns?:number}){return <tr><td colSpan={columns} style={{textAlign:"center",padding:28,color:"var(--muted)"}}>{text}</td></tr>}
function accessFor(slug:string):Capability{if(slug==="employee-relations")return "cases:read";if(slug==="hr-service")return "hr-service:read";if(slug==="policies")return "policies:read";return "workflows:read"}
function AccessDenied({slug,locale}:{slug:string;locale:Locale}){const title=slug==="employee-relations"?c(locale,"Employee Relations","Çalışan İlişkileri"):slug==="hr-service"?c(locale,"HR Service","İK Hizmetleri"):slug==="policies"?c(locale,"Policies","Politikalar"):c(locale,"Workflows","İş Akışları");return <div className="services-shell"><section className="card services-panel" style={{minHeight:270,display:"grid",placeItems:"center",textAlign:"center",padding:36}}><div style={{maxWidth:560}}><LockKeyhole size={30} style={{margin:"0 auto 12px"}}/><span className="section-kicker">{c(locale,"Policy enforced","Politika uygulanıyor")}</span><h3>{c(locale,`${title} access is restricted`,`${title} erişimi kısıtlı`)}</h3><p style={{color:"var(--muted)"}}>{c(locale,"Your authenticated role does not include this governed data capability.","Kimliği doğrulanmış rolünüz bu yönetişim kontrollü veri yetkisini içermiyor.")}</p></div></section></div>}

export async function EmployeeServicesLiveWorkspace({slug}:{slug:string}){
  const [ctx,locale]=await Promise.all([getServerRequestContext(),getServerLocale()]);
  if(!ctx)return <EmployeeServicesWorkspace slug={slug}/>;
  if(!can(ctx,accessFor(slug)))return <AccessDenied slug={slug} locale={locale}/>;

  if(slug==="employee-relations"){
    const data=await getEmployeeRelationsLiveData(ctx);
    return <div className="services-shell">
      <section className="services-metrics"><Metric icon={<FileLock2 size={18}/>} label={c(locale,"Accessible open cases","Erişilebilir açık vakalar")} value={String(data.openCases)} meta="Case Wall"/><Metric icon={<TimerReset size={18}/>} label={c(locale,"Active allegations","Aktif iddialar")} value={String(data.activeAllegations)} meta={c(locale,"Open / investigating","Açık / soruşturma")}/><Metric icon={<Gavel size={18}/>} label={c(locale,"Open actions","Açık aksiyonlar")} value={String(data.openActions)} meta={c(locale,`${data.findings} findings`,`${data.findings} bulgu`)}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Active appeals","Aktif itirazlar")} value={String(data.activeAppeals)} meta={c(locale,"Submitted / reviewing","Gönderildi / inceleniyor")}/></section>
      <section className="services-split"><div className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Restricted live casework","Kısıtlı canlı vaka yönetimi")}</span><h3>{c(locale,"Employee relations case register","Çalışan ilişkileri vaka envanteri")}</h3></div><span className="matrix-note">Case Wall</span></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Case","Vaka")}</th><th>{c(locale,"Type","Tür")}</th><th>{c(locale,"Title","Başlık")}</th><th>{c(locale,"Phase","Aşama")}</th><th>{c(locale,"Age","Yaş")}</th><th>{c(locale,"Findings","Bulgular")}</th><th>{c(locale,"Actions","Aksiyonlar")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{data.rows.length?data.rows.map(row=><tr key={String(row.id)}><td><strong>{String(row.caseNumber)}</strong><small className="cell-sub">{String(row.openedAt)}</small></td><td>{String(row.caseType)}</td><td>{String(row.title)}</td><td>{String(row.phase)}</td><td>{String(row.age)}</td><td>{String(row.findings)}</td><td>{String(row.openActions)}</td><td><Pill value={String(row.status)} locale={locale}/></td></tr>):<Empty text={c(locale,"No cases are assigned to your case wall.","Vaka duvarınıza atanmış vaka bulunmuyor.")}/>}</tbody></table></div></div><aside className="card services-side restricted-case"><div className="services-panel-head"><div><span className="section-kicker">Case Wall</span><h3>{c(locale,"Need-to-know boundary","Bilmesi gereken prensibi")}</h3></div><LockKeyhole size={18}/></div><div className="services-control-stack"><div><ShieldCheck size={17}/><span><strong>{c(locale,"Membership enforced","Üyelik zorunlu")}</strong><small>{c(locale,"Only owned or assigned cases are queried.","Yalnız sahip olunan veya atanmış vakalar sorgulanır.")}</small></span></div><div><FileLock2 size={17}/><span><strong>{c(locale,"Highly restricted","Yüksek kısıtlı")}</strong><small>{c(locale,"Case evidence stays outside generic document visibility.","Vaka kanıtı genel doküman görünürlüğü dışında kalır.")}</small></span></div></div></aside></section>
    </div>;
  }

  if(slug==="hr-service"){
    const data=await getHRServiceLiveData(ctx);
    return <div className="services-shell">
      <section className="services-metrics"><Metric icon={<CircleHelp size={18}/>} label={data.mode==="self"?c(locale,"My open requests","Açık taleplerim"):c(locale,"Open requests","Açık talepler")} value={String(data.openRequests)} meta={data.mode==="self"?c(locale,"Identity-bound self service","Kimliğe bağlı self servis"):c(locale,"Relationship + queue scope","İlişki + kuyruk kapsamı")}/><Metric icon={<Clock3 size={18}/>} label={c(locale,"SLA compliance","SLA uyumu")} value={`${data.slaCompliance}%`} meta={c(locale,`${data.breached} breaches`,`${data.breached} ihlal`)}/><Metric icon={<UsersRound size={18}/>} label={c(locale,"First response","İlk yanıt")} value={data.medianFirstResponse} meta={c(locale,"Median","Medyan")}/><Metric icon={<Route size={18}/>} label={c(locale,"Routed","Yönlendirilen")} value={`${data.routedPercent}%`} meta={c(locale,"Queue or assignee set","Kuyruk veya atanan mevcut")}/></section>
      <section className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Live employee service","Canlı çalışan hizmeti")}</span><h3>{c(locale,"Request operating queue","Talep operasyon kuyruğu")}</h3></div><span className="matrix-note">{data.mode==="self"?c(locale,"Self service","Self servis"):c(locale,"Scoped operations","Kapsamlı operasyon")}</span></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Request","Talep")}</th><th>{c(locale,"Category","Kategori")}</th><th>{c(locale,"Title","Başlık")}</th><th>{c(locale,"Priority","Öncelik")}</th><th>{c(locale,"Age","Yaş")}</th><th>SLA</th><th>{c(locale,"Queue","Kuyruk")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{data.rows.length?data.rows.map(row=><tr key={row.id}><td><strong>{row.requestNumber}</strong></td><td>{row.category}</td><td>{row.title}</td><td>{row.priority}</td><td>{row.age}</td><td>{row.sla}</td><td>{row.queue}</td><td><Pill value={row.status} locale={locale}/></td></tr>):<Empty text={c(locale,"No HR service requests are visible in this scope.","Bu kapsamda görünür İK hizmet talebi bulunmuyor.")}/>}</tbody></table></div></section>
      {data.mode==="operations"?<section className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Queue ownership","Kuyruk sahipliği")}</span><h3>{c(locale,"Delegated service queues","Delege hizmet kuyrukları")}</h3></div><span className="matrix-note">{data.queueManage?c(locale,"Queue admin","Kuyruk yöneticisi"):c(locale,"Membership scoped","Üyelik kapsamlı")}</span></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Queue","Kuyruk")}</th><th>{c(locale,"Owner","Sahip")}</th><th>{c(locale,"Default SLA","Varsayılan SLA")}</th><th>{c(locale,"Members","Üyeler")}</th><th>{c(locale,"Open","Açık")}</th><th>{c(locale,"Breached","İhlal")}</th><th>{c(locale,"Unassigned","Atanmamış")}</th></tr></thead><tbody>{data.queueRows.length?data.queueRows.map(row=><tr key={row.id}><td><strong>{row.name}</strong><small className="cell-sub">{row.key}</small></td><td>{row.owners}</td><td>{row.defaultSla}</td><td>{row.agents}</td><td>{row.open}</td><td>{row.breached}</td><td>{row.unassigned}</td></tr>):<Empty columns={7} text={c(locale,"No service queues are delegated to this actor.","Bu aktöre delege edilmiş hizmet kuyruğu yok.")}/>}</tbody></table></div></section>:null}
    </div>;
  }

  if(slug==="policies"){
    const data=await getPoliciesLiveData(ctx);
    const governed=data.mode==="governance";
    return <div className="services-shell">
      <section className="services-metrics"><Metric icon={<BookOpenCheck size={18}/>} label={data.mode==="self"?c(locale,"Assigned policies","Atanan politikalar"):c(locale,"Published policies","Yayınlanan politikalar")} value={String(data.published)} meta={data.mode==="self"?c(locale,`${data.pending} acknowledgement actions`,`${data.pending} okuma/onay aksiyonu`):governed?c(locale,`${data.pendingApprovals} awaiting review`,`${data.pendingApprovals} inceleme bekliyor`):c(locale,"Effective published register","Geçerli yayın envanteri")}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Review due","İnceleme tarihi yaklaşan")} value={String(data.reviewDue)} meta={c(locale,"Next 60 days","Önümüzdeki 60 gün")}/><Metric icon={<BadgeCheck size={18}/>} label={c(locale,"Acknowledgement","Onaylama oranı")} value={`${data.acknowledgement}%`} meta={c(locale,"Version-bound evidence","Sürüme bağlı kanıt")}/><Metric icon={<ShieldCheck size={18}/>} label={governed?c(locale,"Active exceptions","Aktif istisnalar"):c(locale,"Governance","Yönetişim")} value={governed?String(data.activeExceptions):c(locale,"On","Aktif")} meta={governed?c(locale,`${data.pendingExceptions} pending decisions`,`${data.pendingExceptions} karar bekliyor`):c(locale,"Four-eyes lifecycle","Dört göz yaşam döngüsü")}/></section>
      <section className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Live policy lifecycle","Canlı politika yaşam döngüsü")}</span><h3>{data.mode==="self"?c(locale,"My policy register","Politika envanterim"):c(locale,"Controlled policy register","Kontrollü politika envanteri")}</h3></div><span className="matrix-note">DRAFT → REVIEW → APPROVED → PUBLISHED</span></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>{c(locale,"Code","Kod")}</th><th>{c(locale,"Policy","Politika")}</th><th>{c(locale,"Version","Sürüm")}</th><th>{c(locale,"Jurisdiction","Yargı alanı")}</th><th>{data.mode==="self"?c(locale,"My status","Durumum"):c(locale,"Audience","Hedef kitle")}</th><th>{data.mode==="self"?c(locale,"Effective","Geçerlilik"):c(locale,"Acknowledged","Onaylandı")}</th><th>{c(locale,"Review","İnceleme")}</th><th>{c(locale,"Status","Durum")}</th>{governed?<th>{c(locale,"Governance","Yönetişim")}</th>:null}</tr></thead><tbody>{data.rows.length?data.rows.map(row=><tr key={row.id}><td><strong>{row.code}</strong></td><td>{row.title}</td><td>{row.version}</td><td>{row.jurisdiction}</td><td>{data.mode==="self"?<Pill value={row.assignmentStatus??"Pending"} locale={locale}/>:row.audience}</td><td>{data.mode==="self"?row.effectiveFrom:`${row.acknowledged}%`}</td><td>{row.reviewDueAt}</td><td><Pill value={row.status} locale={locale}/></td>{governed?<td><PolicyReviewActions policyId={row.id} status={row.rawStatus} ownerId={row.ownerId} actorId={data.actorId} canWrite={data.canWrite} canApprove={data.canApprove}/></td>:null}</tr>):<Empty columns={governed?9:8} text={c(locale,"No policies are visible in this scope.","Bu kapsamda görünür politika bulunmuyor.")}/>}</tbody></table></div></section>
      <section className="card services-side"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Governance controls","Yönetişim kontrolleri")}</span><h3>{c(locale,"Human-owned approval boundary","İnsan sahipli onay sınırı")}</h3></div><ShieldCheck size={18}/></div><div className="services-control-stack"><div><CheckCircle2 size={17}/><span><strong>{c(locale,"Four-eyes publication","Dört göz yayın")}</strong><small>{c(locale,"Policy owner and approver must be different actors.","Politika sahibi ve onaylayan farklı aktörler olmalıdır.")}</small></span></div><div><BadgeCheck size={17}/><span><strong>{c(locale,"Version-bound acknowledgement","Sürüme bağlı okundu kanıtı")}</strong><small>{c(locale,"Acknowledgement remains bound to the published policy version.","Okundu kanıtı yayınlanan politika sürümüne bağlı kalır.")}</small></span></div></div></section>
    </div>;
  }

  const data=await getWorkflowsLiveData(ctx);
  return <div className="services-shell"><section className="services-metrics"><Metric icon={<Workflow size={18}/>} label={c(locale,"Active definitions","Aktif tanımlar")} value={String(data.activeDefinitions)} meta={c(locale,"Versioned workflows","Sürümlü iş akışları")}/><Metric icon={<GitBranch size={18}/>} label={c(locale,"In flight","Devam eden")} value={String(data.inFlight)} meta={c(locale,"Pending / running / waiting","Bekliyor / çalışıyor")}/><Metric icon={<Clock3 size={18}/>} label={c(locale,"Waiting tasks","Bekleyen görevler")} value={String(data.waitingTasks)} meta={c(locale,`${data.overdueTasks} overdue`,`${data.overdueTasks} gecikmiş`)}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Failures","Hatalar")} value={String(data.failed)} meta={c(locale,"Instances + tasks","Instance + görev")}/></section><section className="card services-panel"><div className="services-panel-head"><div><span className="section-kicker">{c(locale,"Live workflow registry","Canlı iş akışı envanteri")}</span><h3>{c(locale,"Workflow definitions","İş akışı tanımları")}</h3></div></div><div className="services-table-wrap"><table className="services-table"><thead><tr><th>Key</th><th>{c(locale,"Name","Ad")}</th><th>{c(locale,"Version","Sürüm")}</th><th>{c(locale,"Trigger","Tetikleyici")}</th><th>{c(locale,"Instances","Çalışmalar")}</th><th>{c(locale,"In flight","Devam eden")}</th><th>{c(locale,"Failures","Hatalar")}</th><th>{c(locale,"Status","Durum")}</th></tr></thead><tbody>{data.rows.length?data.rows.map(row=><tr key={row.id}><td><strong>{row.key}</strong></td><td>{row.name}</td><td>{row.version}</td><td>{row.trigger}</td><td>{row.instances}</td><td>{row.inFlight}</td><td>{row.failures}</td><td><Pill value={row.status} locale={locale}/></td></tr>):<Empty text={c(locale,"No workflow definitions found.","İş akışı tanımı bulunamadı.")}/>}</tbody></table></div></section></div>;
}
