import { Activity, AlertTriangle, BarChart3, Bot, BrainCircuit, CheckCircle2, ClipboardCheck, EyeOff, FileKey2, Fingerprint, Gauge, GitBranch, LockKeyhole, MoreHorizontal, Scale, ShieldCheck, Sparkles, Target, UsersRound } from "lucide-react";

export const governancePlanningWorkspaceSlugs = new Set(["engagement", "workforce-planning", "analytics", "ai-assistant", "privacy", "audit"]);

const engagementRows = [
  ["Q3 Pulse", "Open", "438 / 512", "85.5%", "7", "Anonymous"],
  ["Manager Effectiveness", "Closed", "356 / 401", "88.8%", "10", "Anonymous"],
  ["Onboarding 30-day", "Open", "22 / 27", "81.5%", "5", "Confidential"]
];
const planRows = [
  ["FY27 Base", "12 months", "512", "548", "+36", "+₺51.2M", "Review"],
  ["Cloud expansion", "18 months", "512", "573", "+61", "+₺88.4M", "Draft"],
  ["Efficiency", "12 months", "512", "503", "-9", "-₺13.8M", "Draft"]
];
const metricRows = [
  ["Voluntary attrition", "6.8%", "12m rolling", "512", "Visible"],
  ["Time to hire", "31d", "90d", "47 hires", "Visible"],
  ["Engagement score", "78.4", "Q3", "438", "Visible"],
  ["Small team absence", "—", "30d", "4", "Suppressed"]
];
const privacyRows = [
  ["DSR-2026-014", "Access", "Identity verified", "12d", "Privacy", "In progress"],
  ["DSR-2026-013", "Rectification", "Received", "24d", "Privacy", "Open"],
  ["ROPA-EMP-04", "Employee monitoring", "Legitimate interest", "High", "DPIA", "Review"],
  ["XFER-008", "EU → US processor", "SCC", "Medium", "TIA", "Active"]
];
const auditRows = [
  ["16:08:44", "privacy-officer", "privacy.dsr-created", "DataSubjectRequest", "Restricted", "Verified"],
  ["16:04:11", "er-investigator", "employee-case.allegation-added", "CaseAllegation", "Highly restricted", "Verified"],
  ["15:59:02", "hr-ops", "workflow-instance.started", "WorkflowInstance", "Internal", "Verified"],
  ["15:47:26", "comp-admin", "compensation-change.approved", "CompensationChange", "Restricted", "Verified"]
];

function Metric({ icon, label, value, meta }: { icon: React.ReactNode; label: string; value: string; meta: string }) { return <div className="gov-metric card"><div className="gov-metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>; }
function Pill({ value }: { value: string }) { const key=value.toLowerCase().replace(/\s+/g,"-"); return <em className={`gov-pill ${key}`}>{value}</em>; }
function Table({ headers, rows }: { headers:string[]; rows:string[][] }) { return <div className="gov-table-wrap"><table className="gov-table"><thead><tr>{headers.map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.map((r)=><tr key={r.join("-")}>{r.map((v,i)=><td key={i}>{i===r.length-1?<Pill value={v}/>:v}</td>)}</tr>)}</tbody></table></div>; }

function Engagement(){return <><section className="gov-metrics"><Metric icon={<UsersRound size={18}/>} label="Response rate" value="85.5%" meta="Q3 pulse · 438 responses"/><Metric icon={<Gauge size={18}/>} label="Engagement" value="78.4" meta="+2.8 vs previous pulse"/><Metric icon={<EyeOff size={18}/>} label="Suppressed cuts" value="14" meta="Below anonymity threshold"/><Metric icon={<AlertTriangle size={18}/>} label="Action themes" value="6" meta="Human-reviewed themes"/></section><section className="gov-split"><div className="card gov-panel"><div className="gov-panel-head"><div><span className="section-kicker">Employee listening</span><h3>Survey campaigns</h3></div><MoreHorizontal size={18}/></div><Table headers={["Campaign","Status","Responses","Rate","Threshold","Mode"]} rows={engagementRows}/></div><aside className="card gov-side"><div className="gov-panel-head"><div><span className="section-kicker">Privacy by design</span><h3>Anonymity controls</h3></div><EyeOff size={18}/></div><div className="gov-controls"><p><ShieldCheck size={17}/><span><strong>Minimum cohort threshold</strong><small>Results under the configured population size are suppressed.</small></span></p><p><Fingerprint size={17}/><span><strong>No employee ID in anonymous responses</strong><small>Participation tokens remain separated from response content.</small></span></p><p><BrainCircuit size={17}/><span><strong>AI themes, not employee scoring</strong><small>Free text may be summarized only at protected cohort level.</small></span></p></div></aside></section></>}
function Planning(){return <><section className="gov-metrics"><Metric icon={<Target size={18}/>} label="Approved headcount" value="512" meta="Current funded positions"/><Metric icon={<UsersRound size={18}/>} label="FY27 base" value="548" meta="+36 planned FTE"/><Metric icon={<BarChart3 size={18}/>} label="Annual cost delta" value="+₺51.2M" meta="Base planning scenario"/><Metric icon={<Activity size={18}/>} label="Critical skill gaps" value="18" meta="Linked to demand lines"/></section><section className="gov-split"><div className="card gov-panel"><div className="gov-panel-head"><div><span className="section-kicker">Scenario planning</span><h3>Workforce scenarios</h3></div><MoreHorizontal size={18}/></div><Table headers={["Scenario","Horizon","Current","Planned","Delta","Cost delta","Status"]} rows={planRows}/></div><aside className="card gov-side"><div className="gov-panel-head"><div><span className="section-kicker">Planning model</span><h3>Demand → role → cost</h3></div><GitBranch size={18}/></div><div className="planning-chain"><span>Business demand</span><i>→</i><span>Org / Role</span><i>→</i><span>FTE</span><i>→</i><span>Skills</span><i>→</i><span>Cost</span></div><p className="gov-copy">Scenarios remain separate from the live organization until approved. No planning draft silently changes employee or position records.</p></aside></section></>}
function Analytics(){return <><section className="gov-metrics"><Metric icon={<BarChart3 size={18}/>} label="Governed metrics" value="64" meta="Shared semantic definitions"/><Metric icon={<CheckCircle2 size={18}/>} label="Fresh today" value="59" meta="5 awaiting data refresh"/><Metric icon={<EyeOff size={18}/>} label="Privacy suppression" value="7" meta="Small cohorts hidden"/><Metric icon={<Scale size={18}/>} label="Reconciled" value="98.7%" meta="Against system-of-record totals"/></section><section className="gov-split"><div className="card gov-panel"><div className="gov-panel-head"><div><span className="section-kicker">People intelligence</span><h3>Metric catalog & current values</h3></div><MoreHorizontal size={18}/></div><Table headers={["Metric","Value","Period","Population","Privacy"]} rows={metricRows}/></div><aside className="card gov-side"><div className="gov-panel-head"><div><span className="section-kicker">Explainability</span><h3>Metric contract</h3></div><ClipboardCheck size={18}/></div><div className="gov-controls"><p><CheckCircle2 size={17}/><span><strong>One governed definition</strong><small>Formula, unit, aggregation and population threshold travel together.</small></span></p><p><EyeOff size={17}/><span><strong>Small-number protection</strong><small>Suppression is applied before dashboard distribution.</small></span></p><p><ShieldCheck size={17}/><span><strong>No hidden ranking</strong><small>Analytics describes workforce patterns; it does not rank people.</small></span></p></div></aside></section></>}
function AIAssistant(){return <><section className="gov-metrics"><Metric icon={<Bot size={18}/>} label="Assistant requests" value="184" meta="Last 7 days"/><Metric icon={<ShieldCheck size={18}/>} label="Policy-grounded" value="100%" meta="Purpose required per request"/><Metric icon={<LockKeyhole size={18}/>} label="ER case access" value="Blocked" meta="General assistant boundary"/><Metric icon={<Sparkles size={18}/>} label="Autonomous HR decisions" value="0" meta="Human decision ownership"/></section><section className="ai-governance-grid"><div className="card ai-governance-hero"><div className="ai-orb"><Sparkles size={24}/></div><div><span className="section-kicker">HRBP One AI</span><h3>Copilot, not decision maker.</h3><p>The assistant may summarize governed records, draft communications, explain policies and surface workflow context. It does not autonomously hire, fire, promote, rate, discipline or classify an employee.</p></div></div><aside className="card gov-side"><div className="gov-panel-head"><div><span className="section-kicker">Interaction ledger</span><h3>Minimal-retention telemetry</h3></div></div><div className="gov-controls"><p><Fingerprint size={17}/><span><strong>Prompt stored as hash</strong><small>Operational ledger avoids retaining raw prompts by default.</small></span></p><p><FileKey2 size={17}/><span><strong>Purpose & classification</strong><small>Every request carries a business purpose and data boundary.</small></span></p><p><BrainCircuit size={17}/><span><strong>Source references</strong><small>Generated outputs can point back to governed source records.</small></span></p></div></aside></section></>}
function Privacy(){return <><section className="gov-metrics"><Metric icon={<FileKey2 size={18}/>} label="Processing activities" value="42" meta="RoPA records in scope"/><Metric icon={<ClockIcon/>} label="Open DSRs" value="6" meta="1 due within 7 days"/><Metric icon={<Scale size={18}/>} label="DPIA required" value="4" meta="High-risk processing"/><Metric icon={<ShieldCheck size={18}/>} label="Cross-border transfers" value="9" meta="All mapped to safeguards"/></section><section className="gov-split"><div className="card gov-panel"><div className="gov-panel-head"><div><span className="section-kicker">Privacy operations</span><h3>Rights, processing & transfers</h3></div><MoreHorizontal size={18}/></div><Table headers={["Record","Type","Basis / state","Risk / due","Owner","Status"]} rows={privacyRows}/></div><aside className="card gov-side"><div className="gov-panel-head"><div><span className="section-kicker">Employment privacy</span><h3>Lawful basis first</h3></div><Scale size={18}/></div><p className="gov-copy">Employee processing is not modeled as “consent by default.” Contract, legal obligation and legitimate interest can be tracked explicitly, with DPIA and transfer safeguards where required.</p></aside></section></>}
function ClockIcon(){return <Activity size={18}/>}
function Audit(){return <><section className="gov-metrics"><Metric icon={<ClipboardCheck size={18}/>} label="Events today" value="2,841" meta="Business and security actions"/><Metric icon={<ShieldCheck size={18}/>} label="Hash chain" value="Intact" meta="No detected chain break"/><Metric icon={<LockKeyhole size={18}/>} label="Restricted reads" value="73" meta="Purpose-aware sensitive access"/><Metric icon={<AlertTriangle size={18}/>} label="Review flags" value="3" meta="Unusual access patterns"/></section><section className="gov-split"><div className="card gov-panel"><div className="gov-panel-head"><div><span className="section-kicker">Immutable activity ledger</span><h3>Recent governed events</h3></div><MoreHorizontal size={18}/></div><Table headers={["Time","Actor","Action","Resource","Class","Integrity"]} rows={auditRows}/></div><aside className="card gov-side"><div className="gov-panel-head"><div><span className="section-kicker">Audit design</span><h3>Metadata, not secret payloads</h3></div><ShieldCheck size={18}/></div><div className="gov-controls"><p><CheckCircle2 size={17}/><span><strong>Actor + purpose + resource</strong><small>Enough evidence to reconstruct access without copying record payloads into logs.</small></span></p><p><Fingerprint size={17}/><span><strong>Previous-hash chaining</strong><small>Tamper evidence is built into the application audit sequence.</small></span></p></div></aside></section></>}

export function GovernancePlanningWorkspace({slug}:{slug:string}){return <div className="gov-shell">{slug==="engagement"?<Engagement/>:slug==="workforce-planning"?<Planning/>:slug==="analytics"?<Analytics/>:slug==="ai-assistant"?<AIAssistant/>:slug==="privacy"?<Privacy/>:<Audit/>}</div>}
