import { AlertTriangle, BadgeCheck, CheckCircle2, Clock3, CreditCard, KeyRound, Laptop2, LockKeyhole, MoreHorizontal, PackageCheck, ShieldCheck, UserMinus } from "lucide-react";
import { can } from "@/lib/authorization";
import { getServerRequestContext } from "@/lib/server-session";
import { getServerLocale } from "@/lib/i18n-server";
import type { Locale } from "@/lib/i18n";
import { getOffboardingWorkspaceData } from "@/lib/offboarding-live-data";
import { getOffboardingHistoryData } from "@/lib/offboarding-history-data";
import { OffboardingOperationsConsole } from "@/components/offboarding-operations-console";
import { OffboardingFinalSettlementConsole } from "@/components/offboarding-final-settlement-console";
import { OffboardingScheduleAmendmentConsole } from "@/components/offboarding-schedule-amendment-console";
import { OffboardingHistory } from "@/components/offboarding-history";

export const offboardingWorkspaceSlugs = new Set(["offboarding"]);

const demoRows=[["E00418 · Deniz A.","Resignation","30 Sep","12 / 15","1","Notice period"],["E00372 · Emre T.","End of contract","25 Sep","9 / 12","0","Clearance"],["E00294 · Selin K.","Retirement","31 Oct","6 / 14","2","Notice period"],["E00461 · Burak N.","Termination","23 Sep","14 / 14","0","Ready to close"]];
function c(locale:Locale,en:string,tr:string){return locale==="tr"?tr:en}
function sv(locale:Locale,value:string){if(locale!=="tr")return value;const m:Record<string,string>={Resignation:"İstifa","End of contract":"Sözleşme sonu",Retirement:"Emeklilik",Termination:"İş akdi feshi","Notice period":"İhbar süresi",Clearance:"İlişik kesme","Final pay review":"Nihai bordro kontrolü","Ready to close":"Kapatmaya hazır",Open:"Açık",Completed:"Tamamlandı",Waived:"Muaf",Blocked:"Bloke"};return m[value]??value}
function Metric({icon,label,value,meta}:{icon:React.ReactNode;label:string;value:string;meta:string}){return <div className="off-metric card"><div className="off-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function Pill({value,locale}:{value:string;locale:Locale}){return <em className={`off-pill ${value.toLowerCase().replace(/\s+/g,"-")}`}>{sv(locale,value)}</em>}
function ClosureGate({locale}:{locale:Locale}){return <aside className="card off-side"><div className="off-head"><div><span className="section-kicker">{c(locale,"Closure gate","Kapanış kontrolü")}</span><h3>{c(locale,"All controls must clear","Tüm kontroller kapanmalı")}</h3></div><ShieldCheck size={18}/></div><div className="off-controls"><p><KeyRound size={17}/><span><strong>{c(locale,"Logical access","Mantıksal erişim")}</strong><small>{c(locale,"Revoked or explicitly excepted before closure.","Kapanıştan önce iptal edilmeli veya açık istisna verilmelidir.")}</small></span></p><p><Laptop2 size={17}/><span><strong>{c(locale,"Company assets","Şirket varlıkları")}</strong><small>{c(locale,"Returned or formally written off.","İade edilmeli veya resmi olarak kayıttan düşülmelidir.")}</small></span></p><p><PackageCheck size={17}/><span><strong>{c(locale,"Knowledge transfer","Bilgi devri")}</strong><small>{c(locale,"Named handover items must be completed before closure.","İsimli bilgi devri kalemleri kapanıştan önce tamamlanmalıdır.")}</small></span></p><p><CreditCard size={17}/><span><strong>{c(locale,"Final settlement","Nihai hesap")}</strong><small>{c(locale,"Prepared, independently approved and settled by separated payroll authorities.","Ayrılmış bordro yetkileriyle hazırlanmalı, bağımsız onaylanmalı ve tamamlanmalıdır.")}</small></span></p><p><CheckCircle2 size={17}/><span><strong>{c(locale,"Independent termination","Bağımsız sonlandırma")}</strong><small>{c(locale,"The initiator cannot perform final employment termination, and the last working date must be reached.","Süreci başlatan kişi nihai istihdam sonlandırmasını yapamaz ve son çalışma tarihine ulaşılmış olmalıdır.")}</small></span></p></div></aside>}
function DemoOffboarding({locale}:{locale:Locale}){return <div className="off-shell"><section className="card employee-restricted-card"><LockKeyhole size={22}/><div><h3>{c(locale,"Offboarding data is protected","İşten ayrılış verisi korumalı")}</h3><p>{c(locale,"The public staging surface shows synthetic separation records. Sign in with an authorized HR role to access live employee exits and clearance controls.","Herkese açık staging görünümü sentetik ayrılış kayıtları gösterir. Canlı çalışan ayrılışlarına ve ilişik kesme kontrollerine erişmek için yetkili bir İK rolüyle giriş yapın.")}</p></div></section><section className="off-metrics"><Metric icon={<UserMinus size={18}/>} label={c(locale,"Open separations","Açık ayrılışlar")} value="11" meta={c(locale,"Synthetic staging data","Sentetik staging verisi")}/><Metric icon={<Clock3 size={18}/>} label={c(locale,"Leaving this week","Bu hafta ayrılacaklar")} value="4" meta={c(locale,"Synthetic staging data","Sentetik staging verisi")}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Blocking tasks","Bloke eden görevler")} value="7" meta={c(locale,"IT · assets · payroll","BT · varlıklar · bordro")}/><Metric icon={<BadgeCheck size={18}/>} label={c(locale,"Ready to close","Kapatmaya hazır")} value="3" meta={c(locale,"Synthetic staging data","Sentetik staging verisi")}/></section><section className="off-split"><div className="card off-panel"><div className="off-head"><div><span className="section-kicker">{c(locale,"Controlled employee exit","Kontrollü çalışan ayrılışı")}</span><h3>{c(locale,"Separation register","Ayrılış envanteri")}</h3></div><MoreHorizontal size={18}/></div><div className="off-table-wrap"><table className="off-table"><thead><tr><th>{c(locale,"Employee","Çalışan")}</th><th>{c(locale,"Type","Tür")}</th><th>{c(locale,"Last day","Son gün")}</th><th>{c(locale,"Tasks","Görevler")}</th><th>{c(locale,"Open blocks","Açık bloklar")}</th><th>{c(locale,"Stage","Aşama")}</th></tr></thead><tbody>{demoRows.map(row=><tr key={row[0]}>{row.slice(0,5).map((value,index)=><td key={index}>{sv(locale,value)}</td>)}<td><Pill value={row[5]} locale={locale}/></td></tr>)}</tbody></table></div></div><ClosureGate locale={locale}/></section></div>}

export async function OffboardingWorkspace(){
  const [ctx,locale]=await Promise.all([getServerRequestContext(),getServerLocale()]);
  if(!ctx||!can(ctx,"offboarding:read"))return <DemoOffboarding locale={locale}/>;
  try{
    const canWrite=can(ctx,"offboarding:write");
    const canPrepareSettlement=can(ctx,"payroll:prepare");
    const canApproveSettlement=can(ctx,"payroll:approve");
    const canSettleSettlement=can(ctx,"payroll:pay");
    const hasSettlementAuthority=canPrepareSettlement||canApproveSettlement||canSettleSettlement;
    const [data,history]=await Promise.all([
      getOffboardingWorkspaceData(ctx,canWrite),
      getOffboardingHistoryData(ctx,can(ctx,"audit:read")).catch((error)=>{console.error("[HRBP] Terminal offboarding history unavailable; active exit workflow remains online.",error);return null})
    ]);
    return <div className="off-shell">
      <section className="off-metrics"><Metric icon={<UserMinus size={18}/>} label={c(locale,"Open separations","Açık ayrılışlar")} value={String(data.openSeparations)} meta={c(locale,`${data.exitRiskProcesses} exit-date risks`,`${data.exitRiskProcesses} çıkış tarihi riski`)}/><Metric icon={<Clock3 size={18}/>} label={c(locale,"Overdue tasks","Gecikmiş görevler")} value={String(data.overdueTasks)} meta={c(locale,`${data.leavingThisWeek} leaving in 7 days`,`${data.leavingThisWeek} kişi 7 gün içinde ayrılıyor`)}/><Metric icon={<AlertTriangle size={18}/>} label={c(locale,"Blocking tasks","Bloke eden görevler")} value={String(data.blockingTasks)} meta={c(locale,`${data.finalPayReview} awaiting final-pay clearance`,`${data.finalPayReview} nihai hesap temizliği bekliyor`)}/><Metric icon={<BadgeCheck size={18}/>} label={c(locale,"Ready to close","Kapatmaya hazır")} value={String(data.readyToClose)} meta={c(locale,"Operations + final settlement + exit date gates","Operasyon + nihai hesap + çıkış tarihi kontrolleri")}/></section>
      {canWrite?<OffboardingOperationsConsole processes={data.processes} employments={data.eligibleEmployments} actorId={ctx.actorId}/>:null}
      {canWrite?<OffboardingScheduleAmendmentConsole processes={data.processes}/>:null}
      {hasSettlementAuthority?<OffboardingFinalSettlementConsole processes={data.processes} actorId={ctx.actorId} canPrepare={canPrepareSettlement} canApprove={canApproveSettlement} canSettle={canSettleSettlement}/>:null}
      <section className="off-split"><div className="card off-panel"><div className="off-head"><div><span className="section-kicker">{c(locale,"Controlled employee exit","Kontrollü çalışan ayrılışı")}</span><h3>{c(locale,"Live separation register","Canlı ayrılış envanteri")}</h3></div><span className="off-live-badge"><ShieldCheck size={14}/> PostgreSQL</span></div><div className="off-table-wrap"><table className="off-table"><thead><tr><th>{c(locale,"Employee","Çalışan")}</th><th>{c(locale,"Type","Tür")}</th><th>{c(locale,"Last day","Son gün")}</th><th>{c(locale,"Tasks","Görevler")}</th><th>{c(locale,"Open blocks","Açık bloklar")}</th><th>{c(locale,"Stage","Aşama")}</th></tr></thead><tbody>{data.processes.length?data.processes.map(row=><tr key={row.id}><td><strong>{row.employee}</strong><small className="cell-sub">{row.employeeNumber} · {row.position}</small></td><td>{sv(locale,row.type)}</td><td>{row.lastWorkingDate}</td><td>{row.completedTasks} / {row.taskCount}</td><td>{row.openBlockingTasks+row.assetsOpen+row.accessOpen+row.openKnowledgeTransfers}{!row.finalSettlementClear?` · ${c(locale,"final pay", "nihai hesap")}: ${row.finalSettlementStatus}`:""}{row.overdueTasks?` · ${row.overdueTasks} ${c(locale,"overdue","gecikmiş")}`:""}</td><td><Pill value={row.readyToClose?"Ready to close":row.status} locale={locale}/></td></tr>):<tr><td colSpan={6} style={{textAlign:"center",padding:26}}>{c(locale,"No open separations in your authorized employment scope.","Yetkili istihdam kapsamınızda açık ayrılış bulunmuyor.")}</td></tr>}</tbody></table></div></div><ClosureGate locale={locale}/></section>
      {history?<OffboardingHistory data={history} locale={locale}/>:null}
    </div>;
  }catch(error){console.error("[HRBP] Live offboarding workspace failed; using protected staging fallback.",error);return <DemoOffboarding locale={locale}/>}
}
