import { BadgeCheck, CloudCog, FileCheck2, FileLock2, Fingerprint, HardDrive, KeyRound, Link2, LockKeyhole, MoreHorizontal, ScanSearch, ShieldCheck, Signature, UsersRound } from "lucide-react";

export const platformAdminWorkspaceSlugs = new Set(["documents", "settings"]);

const documentRows = [
  ["Employment Agreement - E00482", "Employee record", "v3", "Restricted", "Clean", "Signed"],
  ["Performance Review - 2026", "Performance", "v1", "Confidential", "Clean", "Final"],
  ["Remote Work Addendum", "Policy / contract", "v2", "Restricted", "Clean", "Awaiting signature"],
  ["Medical accommodation", "Case-linked", "v1", "Highly restricted", "Case wall", "Restricted"]
];
const idpRows = [
  ["Corporate Entra ID", "Entra ID", "SSO + SCIM", "MFA required", "2m ago", "Active"],
  ["Break-glass local", "Local", "Emergency only", "Hardware MFA", "14d ago", "Active"],
  ["AcquiredCo Okta", "Okta", "SSO", "MFA required", "1h ago", "Review"]
];
const integrationRows = [
  ["Microsoft 365", "Directory / collaboration", "OAuth ref", "15m", "Healthy"],
  ["Finance ERP", "Payroll GL", "Vault ref", "1h", "Healthy"],
  ["Learning provider", "Course catalog", "OAuth ref", "6h", "Healthy"],
  ["Background check", "Recruiting", "Vault ref", "24h", "Paused"]
];
function Metric({icon,label,value,meta}:{icon:React.ReactNode;label:string;value:string;meta:string}){return <div className="platform-metric card"><div className="platform-metric-icon">{icon}</div><div><span>{label}</span><strong>{value}</strong><small>{meta}</small></div></div>}
function Pill({value}:{value:string}){return <em className={`platform-pill ${value.toLowerCase().replace(/\s+/g,"-")}`}>{value}</em>}
function Documents(){return <><section className="platform-metrics"><Metric icon={<HardDrive size={18}/>} label="Vault objects" value="18,942" meta="All HR document versions"/><Metric icon={<ScanSearch size={18}/>} label="Malware scan" value="100%" meta="No unscanned active version"/><Metric icon={<Signature size={18}/>} label="Signature envelopes" value="23" meta="7 awaiting employee action"/><Metric icon={<FileLock2 size={18}/>} label="Legal hold" value="31" meta="Retention deletion suspended"/></section><section className="platform-split"><div className="card platform-panel"><div className="platform-head"><div><span className="section-kicker">Private document vault</span><h3>Versioned HR records</h3></div><MoreHorizontal size={18}/></div><div className="platform-table-wrap"><table className="platform-table"><thead><tr><th>Document</th><th>Purpose</th><th>Version</th><th>Classification</th><th>Security</th><th>State</th></tr></thead><tbody>{documentRows.map(r=><tr key={r[0]}>{r.slice(0,5).map((v,i)=><td key={i}>{v}</td>)}<td><Pill value={r[5]}/></td></tr>)}</tbody></table></div></div><aside className="card platform-side"><div className="platform-head"><div><span className="section-kicker">Vault controls</span><h3>Record integrity</h3></div><ShieldCheck size={18}/></div><div className="platform-controls"><p><Fingerprint size={17}/><span><strong>Immutable version hash</strong><small>Every version keeps its own content hash and object key.</small></span></p><p><ScanSearch size={17}/><span><strong>Quarantine before use</strong><small>New content stays pending until malware scanning is clean.</small></span></p><p><Signature size={17}/><span><strong>Built-in signature trail</strong><small>Envelope, signer state, event timestamps and IP evidence remain in platform.</small></span></p><p><LockKeyhole size={17}/><span><strong>Case-wall separation</strong><small>Highly restricted case files do not appear in the general vault listing.</small></span></p></div></aside></section></>}
function Settings(){return <><section className="platform-metrics"><Metric icon={<KeyRound size={18}/>} label="Identity providers" value="3" meta="2 federated · 1 break-glass"/><Metric icon={<Link2 size={18}/>} label="Integrations" value="14" meta="12 healthy · 2 attention"/><Metric icon={<ShieldCheck size={18}/>} label="MFA enforcement" value="100%" meta="Privileged and workforce access"/><Metric icon={<CloudCog size={18}/>} label="Data region" value="EU" meta="Tenant residency policy"/></section><section className="settings-grid"><div className="card platform-panel"><div className="platform-head"><div><span className="section-kicker">Identity & provisioning</span><h3>Authentication connections</h3></div><BadgeCheck size={18}/></div><div className="platform-table-wrap"><table className="platform-table compact"><thead><tr><th>Name</th><th>Type</th><th>Provisioning</th><th>Control</th><th>Validated</th><th>Status</th></tr></thead><tbody>{idpRows.map(r=><tr key={r[0]}>{r.slice(0,5).map((v,i)=><td key={i}>{v}</td>)}<td><Pill value={r[5]}/></td></tr>)}</tbody></table></div></div><div className="card platform-panel"><div className="platform-head"><div><span className="section-kicker">Connected systems</span><h3>Integration registry</h3></div><Link2 size={18}/></div><div className="platform-table-wrap"><table className="platform-table compact"><thead><tr><th>Connection</th><th>Purpose</th><th>Credential</th><th>Sync</th><th>Status</th></tr></thead><tbody>{integrationRows.map(r=><tr key={r[0]}>{r.slice(0,4).map((v,i)=><td key={i}>{v}</td>)}<td><Pill value={r[4]}/></td></tr>)}</tbody></table></div></div><aside className="card platform-side security-posture"><div className="platform-head"><div><span className="section-kicker">Tenant security</span><h3>Default posture</h3></div><ShieldCheck size={18}/></div><div className="security-list"><div><span>MFA</span><strong>Required</strong></div><div><span>Restricted export</span><strong>Blocked</strong></div><div><span>Watermarking</span><strong>Enabled</strong></div><div><span>Break glass</span><strong>Enabled</strong></div><div><span>Secrets</span><strong>References only</strong></div></div></aside></section></>}
export function PlatformAdminWorkspace({slug}:{slug:string}){return <div className="platform-shell">{slug==="documents"?<Documents/>:<Settings/>}</div>}
