import { BadgeCheck, BriefcaseBusiness, CalendarClock, CircleAlert, FileCheck2, ShieldCheck, UserPlus, UsersRound } from "lucide-react";
import { onboardingPeople, onboardingTasks, pipeline, requisitions } from "@/lib/recruiting-demo";

function Metric({ label, value, note, icon: Icon }: { label:string; value:string; note:string; icon:React.ComponentType<{size?:number}> }) {
  return <div className="recruit-metric"><span><Icon size={16}/></span><div><small>{label}</small><strong>{value}</strong><em>{note}</em></div></div>;
}

export function RecruitingWorkspace({ slug }: { slug:string }) {
  if (slug === "recruiting") return <>
    <div className="recruit-metrics"><Metric label="Open requisitions" value="12" note="9 approved · 3 pending" icon={BriefcaseBusiness}/><Metric label="Active candidates" value="86" note="+21 this week" icon={UsersRound}/><Metric label="Interviews" value="18" note="Next 7 days" icon={CalendarClock}/><Metric label="Offers" value="6" note="4 awaiting signature" icon={FileCheck2}/></div>
    <div className="recruit-grid"><section className="card pipeline-card"><div className="recruit-title"><div><h3>Candidate pipeline</h3><p>Privacy-governed candidate records linked to approved requisitions.</p></div><span>64 active</span></div><div className="pipeline-board">{pipeline.map((column)=><div className="pipeline-column" key={column.stage}><header><strong>{column.stage}</strong><span>{column.count}</span></header>{column.people.map((person,i)=><article key={person}><div className="candidate-avatar">{person.split(" ").map(n=>n[0]).join("")}</div><div><strong>{person}</strong><small>{i === 0 ? "Senior profile" : "Candidate record"}</small></div><em>{i === 0 ? "2d" : "4d"}</em></article>)}<button>View {column.count} records</button></div>)}</div></section>
    <section className="card requisition-card"><div className="recruit-title"><div><h3>Requisitions</h3><p>Position-backed hiring demand</p></div><button className="secondary-button">Approval queue</button></div><div className="table-wrap"><table className="enterprise-table"><thead><tr><th>Requisition</th><th>Org / location</th><th>Hiring manager</th><th>Recruiter</th><th>Candidates</th><th>Status</th><th>Target</th></tr></thead><tbody>{requisitions.map(r=><tr key={r.id}><td><strong className="cell-strong">{r.title}</strong><small className="cell-sub">{r.id}</small></td><td><strong className="cell-strong">{r.org}</strong><small className="cell-sub">{r.location}</small></td><td>{r.manager}</td><td>{r.recruiter}</td><td>{r.candidates}</td><td><em className={`pill ${r.status.toLowerCase()}`}>{r.status}</em></td><td>{r.target}</td></tr>)}</tbody></table></div></section></div>
    <div className="privacy-strip"><ShieldCheck size={17}/><div><strong>Recruiting privacy boundary</strong><p>Candidate records are classified Restricted, carry retention metadata and only become employee history through the controlled Hire transition.</p></div><span>Policy enforced</span></div>
  </>;

  if (slug === "onboarding") return <>
    <div className="recruit-metrics"><Metric label="Preboarding" value="8" note="Next 30 days" icon={UserPlus}/><Metric label="Tasks complete" value="74%" note="Across active plans" icon={BadgeCheck}/><Metric label="Blockers" value="3" note="2 require HR action" icon={CircleAlert}/><Metric label="Start readiness" value="91%" note="Weighted control score" icon={ShieldCheck}/></div>
    <div className="onboarding-grid"><section className="card"><div className="recruit-title"><div><h3>Onboarding journeys</h3><p>Hire-to-day-one orchestration across People, IT and managers.</p></div><button className="secondary-button">Journey templates</button></div><div className="journey-list">{onboardingPeople.map(p=><article key={p.name}><div className="journey-avatar">{p.initials}</div><div className="journey-person"><strong>{p.name}</strong><small>{p.role} · Starts {p.start}</small></div><div className="journey-owner"><small>Owner</small><strong>{p.owner}</strong></div><div className="journey-progress"><span><i style={{width:`${p.progress}%`}}/></span><small>{p.progress}% ready</small></div><em className={p.blockers ? "journey-blocked" : "journey-healthy"}>{p.blockers ? `${p.blockers} blocker${p.blockers>1?"s":""}` : "On track"}</em></article>)}</div></section><section className="card"><div className="recruit-title"><div><h3>Cross-functional controls</h3><p>Default enterprise onboarding template</p></div></div><div className="task-control-list">{onboardingTasks.map(t=><div key={t.task}><span className={t.risk === "Healthy" ? "task-ok" : "task-watch"}/><div><strong>{t.task}</strong><small>{t.owner} · Due {t.due}</small></div><b>{t.completion}</b></div>)}</div><div className="onboarding-policy"><ShieldCheck size={17}/><p>Sensitive identity documents remain in the restricted vault. IT receives provisioning attributes, not identity-document contents.</p></div></section></div>
  </>;
  return null;
}

export const recruitingWorkspaceSlugs = new Set(["recruiting","onboarding"]);
