import { DataClassification, PlatformRole } from "@prisma/client";
import type { RequestContext } from "@/lib/request-context";
export type Capability=|"people:read"|"people:write"|"organization:read"|"organization:write"|"positions:read"|"positions:write"|"documents:read"|"documents:write"|"documents:sign"|"recruiting:read"|"recruiting:write"|"onboarding:read"|"onboarding:write"|"offboarding:read"|"offboarding:write"|"time:read"|"time:write"|"leave:read"|"leave:write"|"compensation:read"|"compensation:write"|"payroll:read"|"payroll:write"|"benefits:read"|"benefits:write"|"performance:read"|"performance:write"|"talent:read"|"talent:write"|"succession:read"|"succession:write"|"learning:read"|"learning:write"|"cases:read"|"cases:write"|"hr-service:read"|"hr-service:write"|"policies:read"|"policies:write"|"policies:acknowledge"|"engagement:read"|"engagement:write"|"workforce-plan:read"|"workforce-plan:write"|"analytics:read"|"ai:use"|"privacy:read"|"privacy:write"|"workflows:read"|"workflows:write"|"workflows:run"|"settings:read"|"settings:write"|"audit:read";
const grants:Record<PlatformRole,Capability[]>={
EMPLOYEE:["people:read","documents:read","onboarding:read","time:read","leave:read","hr-service:read","hr-service:write","policies:read","policies:acknowledge","engagement:read","ai:use"],
MANAGER:["people:read","organization:read","positions:read","documents:read","recruiting:read","onboarding:read","offboarding:read","time:read","time:write","leave:read","leave:write","hr-service:read","hr-service:write","policies:read","policies:acknowledge","engagement:read","analytics:read","ai:use"],
HRBP:["people:read","people:write","organization:read","positions:read","documents:read","documents:write","documents:sign","recruiting:read","recruiting:write","onboarding:read","onboarding:write","offboarding:read","offboarding:write","time:read","leave:read","leave:write","compensation:read","benefits:read","performance:read","performance:write","talent:read","talent:write","succession:read","succession:write","learning:read","hr-service:read","hr-service:write","policies:read","engagement:read","engagement:write","workforce-plan:read","workforce-plan:write","analytics:read","ai:use","privacy:read","workflows:read","workflows:run"],
HR_OPERATIONS:["people:read","people:write","organization:read","organization:write","positions:read","positions:write","documents:read","documents:write","documents:sign","recruiting:read","recruiting:write","onboarding:read","onboarding:write","offboarding:read","offboarding:write","time:read","time:write","leave:read","leave:write","compensation:read","benefits:read","benefits:write","performance:read","learning:read","learning:write","hr-service:read","hr-service:write","policies:read","policies:write","engagement:read","engagement:write","workforce-plan:read","workforce-plan:write","analytics:read","ai:use","privacy:read","workflows:read","workflows:write","workflows:run","settings:read"],
RECRUITER:["people:read","organization:read","positions:read","documents:read","recruiting:read","recruiting:write","onboarding:read","policies:read","ai:use"],TIME_ADMIN:["people:read","organization:read","time:read","time:write","leave:read","leave:write","policies:read"],TALENT_ADMIN:["people:read","organization:read","positions:read","performance:read","performance:write","talent:read","talent:write","succession:read","succession:write","learning:read","learning:write","policies:read","engagement:read","engagement:write","analytics:read","ai:use"],COMPENSATION_ADMIN:["people:read","organization:read","positions:read","compensation:read","compensation:write","payroll:read","benefits:read","policies:read","analytics:read"],PAYROLL_ADMIN:["people:read","organization:read","time:read","leave:read","compensation:read","payroll:read","payroll:write","benefits:read","offboarding:read","policies:read"],ER_INVESTIGATOR:["people:read","cases:read","cases:write","documents:read","documents:write","policies:read"],LEGAL:["people:read","cases:read","documents:read","documents:write","documents:sign","policies:read","policies:write","privacy:read","audit:read"],PRIVACY_OFFICER:["people:read","cases:read","documents:read","policies:read","privacy:read","privacy:write","audit:read"],SECURITY_AUDITOR:["settings:read","audit:read"],TENANT_ADMIN:["people:read","people:write","organization:read","organization:write","positions:read","positions:write","documents:read","documents:write","recruiting:read","recruiting:write","onboarding:read","onboarding:write","offboarding:read","time:read","time:write","leave:read","leave:write","benefits:read","performance:read","talent:read","succession:read","learning:read","hr-service:read","hr-service:write","policies:read","engagement:read","workforce-plan:read","analytics:read","ai:use","privacy:read","workflows:read","workflows:write","settings:read","settings:write","audit:read"]};
const highlyRestrictedReaders=new Set<PlatformRole>([PlatformRole.ER_INVESTIGATOR,PlatformRole.LEGAL,PlatformRole.PRIVACY_OFFICER]);export function can(ctx:RequestContext,capability:Capability){return grants[ctx.role].includes(capability)}export function canReadClassification(ctx:RequestContext,classification:DataClassification){if(classification!==DataClassification.HIGHLY_RESTRICTED)return true;return highlyRestrictedReaders.has(ctx.role)}export function forbidden(message="Access denied by policy."){return Response.json({error:message},{status:403})}
