import type { Locale } from "@/lib/i18n";

const turkish: Record<string, string> = {
  "Policy enforced": "Politika uygulanıyor",
  "access is restricted": "alanına erişim kısıtlı",
  "The signed session does not include this governed capability. Privileged demo data is never substituted when authorization is denied.": "İmzalı oturumunuz bu yetkiyi içermiyor. Erişim reddedildiğinde ayrıcalıklı demo verileri gösterilmez.",
  "Campaign focus is unavailable in your governed scope.": "Seçilen kampanya erişim kapsamınızda bulunmuyor.",
  "The deep link failed closed and did not broaden the engagement query.": "Doğrudan bağlantı reddedildi; bağlılık sorgusunun kapsamı genişletilmedi.",
  "Active campaigns": "Aktif kampanyalar",
  "Visible responses": "Görünür yanıtlar",
  "Suppressed campaigns": "Gizlenen kampanyalar",
  "Raw counts hidden below threshold": "Eşik altındaki ham sayılar gizlenir",
  "Anonymous campaigns": "Anonim kampanyalar",
  "Identity separated from response content": "Kimlik bilgisi yanıt içeriğinden ayrılır",
  "Live employee listening": "Canlı çalışan geri bildirimi",
  "Survey campaigns": "Anket kampanyaları",
  "Campaign": "Kampanya",
  "Survey": "Anket",
  "Responses": "Yanıtlar",
  "Rate": "Oran",
  "Threshold": "Eşik",
  "Mode": "Mod",
  "Window": "Dönem",
  "Status": "Durum",
  "Lifecycle": "Yaşam döngüsü",
  "No campaigns are visible inside your authorized population.": "Yetkili çalışan kapsamınızda görünür kampanya bulunmuyor.",
  "Privacy by design": "Tasarımda gizlilik",
  "Anonymity controls": "Anonimlik kontrolleri",
  "Threshold before disclosure": "Açıklamadan önce eşik kontrolü",
  "Anonymous response counts and rates remain hidden while the authorized cohort is below the campaign threshold.": "Yetkili grup kampanya eşiğinin altında kaldığında anonim yanıt sayıları ve oranları gizlenir.",
  "Scope-bound counting": "Kapsama bağlı sayım",
  "Relationship-scoped viewers count only responses that can be bound to an authorized employment. Unattributed anonymous responses are not borrowed from tenant totals.": "İlişki kapsamı olan kullanıcılar yalnızca yetkili bir istihdamla ilişkilendirilebilen yanıtları sayar. İlişkilendirilmemiş anonim yanıtlar kurum toplamından alınmaz.",
  "No answer-level exposure": "Bireysel yanıtlar gösterilmez",
  "This view never renders individual survey answers or employee-level engagement scoring.": "Bu görünüm bireysel anket yanıtlarını veya çalışan düzeyinde bağlılık puanlarını göstermez.",
  "Scenario focus is unavailable in your governed scope.": "Seçilen senaryo erişim kapsamınızda bulunmuyor.",
  "The deep link failed closed and did not broaden the workforce planning query.": "Doğrudan bağlantı reddedildi; iş gücü planlama sorgusunun kapsamı genişletilmedi.",
  "Active workforce": "Aktif iş gücü",
  "Visible scenarios": "Görünür senaryolar",
  "Primary planned FTE": "Birincil planlanan TZE",
  "Primary cost delta": "Birincil maliyet farkı",
  "Live scenario planning": "Canlı senaryo planlaması",
  "Workforce scenarios": "İş gücü senaryoları",
  "Scenario": "Senaryo",
  "Horizon": "Plan dönemi",
  "Current FTE": "Mevcut TZE",
  "Planned FTE": "Planlanan TZE",
  "Delta": "Fark",
  "Cost delta": "Maliyet farkı",
  "Owner": "Sorumlu",
  "Governance": "Yönetişim",
  "· base": "· başlangıç",
  "m": "ay",
  "No workforce scenario lines intersect your authorized organization or position scope.": "Yetkili organizasyon veya pozisyon kapsamınızla eşleşen iş gücü senaryosu satırı bulunmuyor.",
  "Planning boundary": "Planlama sınırı",
  "Demand → role → cost": "İhtiyaç → rol → maliyet",
  "Authorized org": "Yetkili organizasyon",
  "Role": "Rol",
  "FTE": "TZE",
  "Skills": "Yetkinlikler",
  "Cost": "Maliyet",
  "Relationship-scoped users only see scenario lines intersecting their authorized organization or position set. Scenario approval remains evidence and never mutates the authoritative workforce implicitly.": "İlişki kapsamı olan kullanıcılar yalnızca yetkili organizasyon veya pozisyonlarıyla kesişen senaryo satırlarını görür. Senaryo onayı kanıt olarak saklanır; canlı iş gücü kaydını kendiliğinden değiştirmez.",
  "My requests": "Taleplerim",
  "Authenticated actor · last 7 days": "Kimliği doğrulanmış kullanıcı · son 7 gün",
  "Completed": "Tamamlanan",
  "Decision-support interactions": "Karar desteği etkileşimleri",
  "Blocked": "Engellenen",
  "Decision support only": "Yalnızca karar desteği",
  "No autonomous employment decisions": "Otonom istihdam kararı verilmez",
  "My interaction ledger": "Etkileşim kayıtlarım",
  "Minimal-retention AI telemetry": "Asgari saklamalı yapay zekâ telemetrisi",
  "Actor scoped": "Kullanıcı kapsamında",
  "Purpose": "Amaç",
  "Module": "Modül",
  "Class": "Sınıf",
  "Prompt fingerprint": "İstem özeti",
  "Model": "Model",
  "Created": "Oluşturulma",
  "No AI interaction telemetry is recorded for your account in the last 7 days.": "Hesabınız için son 7 günde yapay zekâ etkileşim kaydı bulunmuyor.",
  "HRBP One AI": "HRBP One Yapay Zekâ",
  "Copilot, not decision maker.": "Yardımcıdır; karar verici değildir.",
  "Operational telemetry is actor-scoped and stores fingerprints plus control context instead of raw prompts. Highly restricted ER and privacy operations remain outside the general assistant boundary.": "Operasyonel telemetri kullanıcı kapsamındadır; ham istem yerine özet değerleri ve kontrol bağlamını saklar. Yüksek kısıtlı çalışan ilişkileri ve gizlilik işlemleri genel asistanın kapsamı dışındadır.",
  "Prompt hashed": "İstem özeti alınır",
  "Raw prompt retention is disabled in the operational ledger.": "Operasyonel kayıtta ham istem saklama kapalıdır.",
  "Purpose required": "Amaç zorunludur",
  "Every request carries a declared business purpose and classification.": "Her talep beyan edilmiş bir iş amacı ve sınıflandırma içerir.",
  "Human-owned decisions": "Kararlar insana aittir",
  "No autonomous hire, fire, promotion, rating or disciplinary outcome.": "İşe alım, işten çıkarma, terfi, değerlendirme veya disiplin sonucu otonom belirlenmez.",
  "Privacy focus is unavailable in your governed scope.": "Seçilen gizlilik kaydı erişim kapsamınızda bulunmuyor.",
  "The deep link failed closed and did not broaden the privacy query.": "Doğrudan bağlantı reddedildi; gizlilik sorgusunun kapsamı genişletilmedi.",
  "Processing activities": "İşleme faaliyetleri",
  "Active RoPA records": "Aktif işleme faaliyeti kayıtları",
  "Open DSRs": "Açık veri sahibi talepleri",
  "DPIA required": "DPIA gerekli",
  "Open high-risk privacy assessments": "Açık yüksek riskli gizlilik değerlendirmeleri",
  "Active transfers": "Aktif aktarımlar",
  "Cross-border transfer register": "Sınır ötesi aktarım kaydı",
  "Live privacy operations": "Canlı gizlilik işlemleri",
  "Data subject requests": "Veri sahibi talepleri",
  "Privacy / Legal only": "Yalnızca Gizlilik / Hukuk",
  "Request": "Talep",
  "Type": "Tür",
  "State": "Aşama",
  "Age": "Yaş",
  "Due": "Son tarih",
  "d": "g",
  "No data subject requests are recorded.": "Kayıtlı veri sahibi talebi bulunmuyor.",
  "Separation of duties": "Görevler ayrılığı",
  "Privacy operations boundary": "Gizlilik işlemleri sınırı",
  "Privacy / Legal roles only": "Yalnızca Gizlilik / Hukuk rolleri",
  "General HRBP, HR Operations and tenant administration do not inherit DSR, RoPA or transfer-register visibility.": "Genel İK İş Ortağı, İK Operasyonları ve tenant yöneticisi rolleri veri sahibi talepleri, işleme faaliyeti veya aktarım kayıtlarını otomatik olarak göremez.",
  "Lawful basis first": "Önce hukuki dayanak",
  "Processing purpose, legal basis, transfer mechanism and DPIA signals remain explicit records.": "İşleme amacı, hukuki dayanak, aktarım mekanizması ve DPIA göstergeleri ayrı kayıtlar olarak tutulur.",
  "Operational traceability": "Operasyonel izlenebilirlik",
  "Request ownership and due dates remain visible only inside the dedicated privacy boundary.": "Talep sahipliği ve son tarihler yalnızca özel gizlilik yetkisi kapsamında görünür.",
  "Privacy assurance": "Gizlilik güvencesi",
  "DPIA & privacy risk assessments": "DPIA ve gizlilik riski değerlendirmeleri",
  "Owner + due date": "Sorumlu + son tarih",
  "Assessment": "Değerlendirme",
  "Risk": "Risk",
  "DPIA": "DPIA",
  "Focused privacy assessment": "Seçilen gizlilik değerlendirmesi",
  "No privacy risk assessments are recorded.": "Kayıtlı gizlilik riski değerlendirmesi bulunmuyor.",
  "Cross-border assurance": "Sınır ötesi aktarım güvencesi",
  "Transfer impact review register": "Aktarım etki incelemesi kaydı",
  "TIA due-date control": "TIA son tarih kontrolü",
  "Transfer": "Aktarım",
  "Route": "Güzergâh",
  "Recipient": "Alıcı",
  "Mechanism": "Mekanizma",
  "TIA due": "TIA son tarihi",
  "Focused transfer impact review": "Seçilen aktarım etki incelemesi",
  "No active cross-border transfer records are configured.": "Yapılandırılmış aktif sınır ötesi aktarım kaydı bulunmuyor.",
  "Engagement": "Bağlılık",
  "Workforce Planning": "İş Gücü Planlama",
  "AI Assistant": "Yapay Zekâ Asistanı",
  "Privacy & Compliance": "Gizlilik ve Uyum",
  "Relationship scoped": "İlişki kapsamında",
  "Tenant authorized": "Kurum kapsamında",
  "Focused campaign action": "Seçilen kampanya işlemi",
  "Focused campaign": "Seçilen kampanya",
  "Suppressed": "Gizlendi",
  "No scoped scenario selected": "Kapsam dahilinde senaryo seçilmedi",
  "No scoped plan data": "Kapsam dahilinde plan verisi yok",
  "focused review": "seçilen inceleme",
  "focused scenario": "seçilen senaryo",
  "Focused DSR action": "Seçilen veri sahibi talebi işlemi",
  "Focused DSR": "Seçilen veri sahibi talebi",
  "Required": "Gerekli",
  "Not required": "Gerekli değil",
  "Open": "Açık",
  "Closed": "Kapalı",
  "Draft": "Taslak",
  "Approved": "Onaylandı",
  "Archived": "Arşivlendi",
  "Active": "Aktif",
  "Failed": "Başarısız",
  "Received": "Alındı",
  "Processing": "İşleniyor",
  "Anonymous": "Anonim",
  "Identified": "Kimlikli",
  "Internal": "Kurum içi",
  "Confidential": "Gizli",
  "Restricted": "Kısıtlı"
};

export function governanceText(locale: Locale, value: string): string {
  return locale === "tr" ? turkish[value] ?? value : value;
}
