import { Activity, BadgeDollarSign, BarChart3, BookOpenCheck, BriefcaseBusiness, Building2, CalendarDays, ChartNoAxesCombined, CircleHelp, ClipboardCheck, ContactRound, FileKey2, FileText, GraduationCap, HeartHandshake, LayoutDashboard, Network, PackageCheck, PanelsTopLeft, ReceiptText, Settings, ShieldCheck, Sparkles, Target, TimerReset, UserMinus, UserRoundSearch, UsersRound, Workflow } from "lucide-react";
import type { TranslationKey } from "@/lib/i18n";

export type NavItem={labelKey:TranslationKey;slug:string;icon:React.ComponentType<{size?:number;strokeWidth?:number}>;badge?:string};
export type NavGroup={labelKey:TranslationKey;items:NavItem[]};

export const navigation:NavGroup[]=[
{labelKey:"nav.workspace",items:[{labelKey:"nav.commandCenter",slug:"dashboard",icon:LayoutDashboard},{labelKey:"nav.people",slug:"people",icon:UsersRound},{labelKey:"nav.organization",slug:"organization",icon:Network},{labelKey:"nav.employee360",slug:"employee-360",icon:ContactRound}]},
{labelKey:"nav.hireLifecycle",items:[{labelKey:"nav.recruiting",slug:"recruiting",icon:UserRoundSearch,badge:"12"},{labelKey:"nav.onboarding",slug:"onboarding",icon:PackageCheck,badge:"8"},{labelKey:"nav.offboarding",slug:"offboarding",icon:UserMinus,badge:"4"},{labelKey:"nav.positions",slug:"positions",icon:BriefcaseBusiness}]},
{labelKey:"nav.workPay",items:[{labelKey:"nav.timeAttendance",slug:"time-attendance",icon:TimerReset},{labelKey:"nav.leave",slug:"leave",icon:CalendarDays},{labelKey:"nav.payroll",slug:"payroll",icon:ReceiptText},{labelKey:"nav.compensation",slug:"compensation",icon:BadgeDollarSign},{labelKey:"nav.benefits",slug:"benefits",icon:HeartHandshake}]},
{labelKey:"nav.growRetain",items:[{labelKey:"nav.performance",slug:"performance",icon:Target},{labelKey:"nav.talent",slug:"talent",icon:ChartNoAxesCombined},{labelKey:"nav.succession",slug:"succession",icon:Activity},{labelKey:"nav.skillsLearning",slug:"learning",icon:GraduationCap},{labelKey:"nav.engagement",slug:"engagement",icon:BarChart3}]},
{labelKey:"nav.employeeServices",items:[{labelKey:"nav.employeeRelations",slug:"employee-relations",icon:ShieldCheck,badge:"3"},{labelKey:"nav.hrService",slug:"hr-service",icon:CircleHelp},{labelKey:"nav.documents",slug:"documents",icon:FileText},{labelKey:"nav.policies",slug:"policies",icon:BookOpenCheck}]},
{labelKey:"nav.planAutomate",items:[{labelKey:"nav.workforcePlanning",slug:"workforce-planning",icon:Building2},{labelKey:"nav.peopleAnalytics",slug:"analytics",icon:PanelsTopLeft},{labelKey:"nav.aiAssistant",slug:"ai-assistant",icon:Sparkles},{labelKey:"nav.workflows",slug:"workflows",icon:Workflow}]},
{labelKey:"nav.governance",items:[{labelKey:"nav.privacyCompliance",slug:"privacy",icon:FileKey2},{labelKey:"nav.audit",slug:"audit",icon:ClipboardCheck},{labelKey:"nav.settings",slug:"settings",icon:Settings}]}];
