import { Activity, BadgeDollarSign, BarChart3, BookOpenCheck, BriefcaseBusiness, Building2, CalendarDays, ChartNoAxesCombined, CircleHelp, ClipboardCheck, ContactRound, FileKey2, FileText, GraduationCap, HeartHandshake, LayoutDashboard, Network, PackageCheck, PanelsTopLeft, ReceiptText, Settings, ShieldCheck, Sparkles, Target, TimerReset, UserMinus, UserRoundSearch, UsersRound, Workflow } from "lucide-react";
import type { Capability } from "@/lib/authorization";
import type { TranslationKey } from "@/lib/i18n";

export type NavItem={labelKey:TranslationKey;slug:string;icon:React.ComponentType<{size?:number;strokeWidth?:number}>;badge?:string;requiredCapability?:Capability};
export type NavGroup={labelKey:TranslationKey;items:NavItem[]};

export const navigation:NavGroup[]=[
{labelKey:"nav.workspace",items:[{labelKey:"nav.commandCenter",slug:"dashboard",icon:LayoutDashboard},{labelKey:"nav.people",slug:"people",icon:UsersRound,requiredCapability:"people:read"},{labelKey:"nav.organization",slug:"organization",icon:Network,requiredCapability:"organization:read"},{labelKey:"nav.employee360",slug:"employee-360",icon:ContactRound,requiredCapability:"people:read"}]},
{labelKey:"nav.hireLifecycle",items:[{labelKey:"nav.recruiting",slug:"recruiting",icon:UserRoundSearch,requiredCapability:"recruiting:read"},{labelKey:"nav.onboarding",slug:"onboarding",icon:PackageCheck,requiredCapability:"onboarding:read"},{labelKey:"nav.offboarding",slug:"offboarding",icon:UserMinus,requiredCapability:"offboarding:read"},{labelKey:"nav.positions",slug:"positions",icon:BriefcaseBusiness,requiredCapability:"positions:read"}]},
{labelKey:"nav.workPay",items:[{labelKey:"nav.timeAttendance",slug:"time-attendance",icon:TimerReset,requiredCapability:"time:read"},{labelKey:"nav.leave",slug:"leave",icon:CalendarDays,requiredCapability:"leave:read"},{labelKey:"nav.payroll",slug:"payroll",icon:ReceiptText,requiredCapability:"payroll:read"},{labelKey:"nav.compensation",slug:"compensation",icon:BadgeDollarSign,requiredCapability:"compensation:read"},{labelKey:"nav.benefits",slug:"benefits",icon:HeartHandshake,requiredCapability:"benefits:read"}]},
{labelKey:"nav.growRetain",items:[{labelKey:"nav.performance",slug:"performance",icon:Target,requiredCapability:"performance:read"},{labelKey:"nav.talent",slug:"talent",icon:ChartNoAxesCombined,requiredCapability:"talent:read"},{labelKey:"nav.succession",slug:"succession",icon:Activity,requiredCapability:"succession:read"},{labelKey:"nav.skillsLearning",slug:"learning",icon:GraduationCap,requiredCapability:"learning:read"},{labelKey:"nav.engagement",slug:"engagement",icon:BarChart3,requiredCapability:"engagement:read"}]},
{labelKey:"nav.employeeServices",items:[{labelKey:"nav.employeeRelations",slug:"employee-relations",icon:ShieldCheck,requiredCapability:"cases:read"},{labelKey:"nav.hrService",slug:"hr-service",icon:CircleHelp,requiredCapability:"hr-service:read"},{labelKey:"nav.documents",slug:"documents",icon:FileText,requiredCapability:"documents:read"},{labelKey:"nav.policies",slug:"policies",icon:BookOpenCheck,requiredCapability:"policies:read"}]},
{labelKey:"nav.planAutomate",items:[{labelKey:"nav.workforcePlanning",slug:"workforce-planning",icon:Building2,requiredCapability:"workforce-plan:read"},{labelKey:"nav.peopleAnalytics",slug:"analytics",icon:PanelsTopLeft,requiredCapability:"analytics:read"},{labelKey:"nav.aiAssistant",slug:"ai-assistant",icon:Sparkles,requiredCapability:"ai:use"},{labelKey:"nav.workflows",slug:"workflows",icon:Workflow}]},
{labelKey:"nav.governance",items:[{labelKey:"nav.privacyCompliance",slug:"privacy",icon:FileKey2,requiredCapability:"privacy:read"},{labelKey:"nav.audit",slug:"audit",icon:ClipboardCheck,requiredCapability:"audit:read"},{labelKey:"nav.settings",slug:"settings",icon:Settings,requiredCapability:"settings:read"}]}];
