import test from"node:test";import assert from"node:assert/strict";import{readFileSync}from"node:fs";import{runInNewContext}from"node:vm";import{setImmediate as tick}from"node:timers/promises";import ts from"typescript";
function load(path,mocks={},globals={}){const code=ts.transpileModule(readFileSync(path,"utf8"),{fileName:path,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText,module={exports:{}};runInNewContext(code,{module,exports:module.exports,require(name){if(Object.hasOwn(mocks,name))return mocks[name];throw Error("Unexpected "+name)},AbortController,Event,...globals},{filename:path});return module.exports;}
const comp=load("lib/action-center-compensation-control.ts"),pay=load("lib/action-center-payroll-control.ts"),plain=v=>JSON.parse(JSON.stringify(v));
const compItem=(x={})=>({kind:"compensation",action:{type:"approve-compensation",changeId:"c1"},secondaryAction:{type:"reject-compensation",changeId:"c1"},...x});
test("comp adapter projects queue authority",()=>{assert.deepEqual(plain(comp.actionCenterCompensationControl(compItem())),{changeId:"c1",allowedActions:["APPROVE","REJECT"]});assert.deepEqual(plain(comp.actionCenterCompensationControl(compItem({action:{type:"apply-compensation",changeId:"c1"},secondaryAction:null}))),{changeId:"c1",allowedActions:["APPLY"]});});
for(const x of[null,{},compItem({secondaryAction:{type:"reject-compensation",changeId:"c2"}}),compItem({action:{type:"apply-compensation",changeId:"c1"}}),compItem({kind:"leave"})])test("comp adapter fails closed",()=>assert.equal(comp.actionCenterCompensationControl(x),null));
test("comp metadata is fenced from generic handlers",()=>assert.equal(comp.isActionCenterCompensationItem(compItem()),true));
test("payroll adapter projects one state-specific action",()=>{assert.deepEqual(plain(pay.actionCenterPayrollControl({kind:"payroll",action:{type:"approve-payroll",runId:"r1"}})),{runId:"r1",target:"APPROVED"});assert.deepEqual(plain(pay.actionCenterPayrollControl({kind:"payroll",action:{type:"mark-payroll-paid",runId:"r1"}})),{runId:"r1",target:"PAID"});});
for(const x of[null,{}, {kind:"payroll",action:{type:"approve-payroll",runId:""}},{kind:"payroll",action:{type:"approve-payroll",runId:"r1"},secondaryAction:{}},{kind:"leave",action:{type:"approve-payroll",runId:"r1"}}])test("payroll adapter fails closed",()=>assert.equal(pay.actionCenterPayrollControl(x),null));
test("payroll metadata is fenced from generic handlers",()=>assert.equal(pay.isActionCenterPayrollItem({kind:"payroll",action:{type:"approve-payroll",runId:"r1"}}),true));

const jsx=(type,props,key)=>({type,props:props||{},key}),descend=n=>!n||typeof n!=="object"?[]:Array.isArray(n)?n.flatMap(descend):[n,...descend(n.props?.children)];
function compHarness({registry=new Map(),allowedActions=["APPROVE","REJECT"],submit=async()=>({outcome:"unknown"}),confirm=true}={}){const state=[],refs=[],cleanups=[],calls=[];let si=0,ri=0,initial=true,tree,reloads=0;const mod=load("components/compensation-action-center-buttons.tsx",{react:{useState(v){const i=si++;if(initial)state[i]=typeof v==="function"?v():v;return[state[i],v=>{state[i]=typeof v==="function"?v(state[i]):v;}]},useRef(v){const i=ri++;if(initial)refs[i]={current:v};return refs[i]},useEffect(fn){if(initial)cleanups.push(fn());}},"react/jsx-runtime":{jsx,jsxs:jsx},"next/navigation":{useRouter:()=>({refresh(){}})},"lucide-react":{Check:"c",Play:"p",X:"x"},"@/components/locale-provider":{useLocale:()=>({locale:"en"})},"@/lib/compensation-client-action":{async submitCompensationAction(...a){calls.push(a);return submit(...a)},async acknowledgeCompensationNotification(){return true},compensationActionMessage:r=>r.outcome}},{window:{confirm:()=>confirm,dispatchEvent(){},location:{reload(){reloads++;}}}});const w=mod.CompensationActionCenterButtons({changeId:"c1",allowedActions,attemptRegistry:registry});const render=()=>{si=ri=0;tree=w.type(w.props);initial=false;};render();return{calls,registry,button:a=>descend(tree).find(n=>n.props["data-compensation-action"]===a),result:()=>descend(tree).find(n=>n.props["data-compensation-action-result"])?.props["data-compensation-action-result"],async flush(){await tick();render()},unmount(){cleanups.forEach(fn=>fn?.())},get reloads(){return reloads;}};}
test("comp unknown seals across remount",async()=>{const registry=new Map(),h=compHarness({registry});h.button("APPROVE").props.onClick();await h.flush();h.unmount();const r=compHarness({registry});assert.equal(r.result(),"unknown");assert.equal(r.button("REJECT"),undefined);assert.equal(h.calls.length,1);});
test("comp same registry blocks opposite action",()=>{const registry=new Map(),a=compHarness({registry}),b=compHarness({registry});a.button("APPROVE").props.onClick();b.button("REJECT").props.onClick();assert.equal(a.calls.length,1);assert.equal(b.calls.length,0);});
test("apply-only compensation never invents approval",()=>{const h=compHarness({allowedActions:["APPLY"]});assert.ok(h.button("APPLY"));assert.equal(h.button("APPROVE"),undefined);assert.equal(h.button("REJECT"),undefined);});

function payHarness({registry=new Map(),target="APPROVED",submit=async()=>({outcome:"unknown"})}={}){const state=[],refs=[],cleanups=[],calls=[];let si=0,ri=0,initial=true,tree;const mod=load("components/payroll-action-center-button.tsx",{react:{useState(v){const i=si++;if(initial)state[i]=typeof v==="function"?v():v;return[state[i],v=>{state[i]=typeof v==="function"?v(state[i]):v;}]},useRef(v){const i=ri++;if(initial)refs[i]={current:v};return refs[i]},useEffect(fn){if(initial)cleanups.push(fn());}},"react/jsx-runtime":{jsx,jsxs:jsx},"next/navigation":{useRouter:()=>({refresh(){}})},"lucide-react":{Check:"c",ReceiptText:"r"},"@/components/locale-provider":{useLocale:()=>({locale:"en"})},"@/lib/payroll-client-action":{async submitPayrollTransition(...a){calls.push(a);return submit(...a)},async acknowledgePayrollNotification(){return true},payrollActionMessage:r=>r.outcome}},{window:{confirm:()=>true,dispatchEvent(){},location:{reload(){}}}});const w=mod.PayrollActionCenterButton({runId:"r1",target,attemptRegistry:registry});const render=()=>{si=ri=0;tree=w.type(w.props);initial=false;};render();return{calls,registry,button:()=>descend(tree).find(n=>n.props["data-payroll-action"]),result:()=>descend(tree).find(n=>n.props["data-payroll-action-result"])?.props["data-payroll-action-result"],async flush(){await tick();render()},unmount(){cleanups.forEach(fn=>fn?.())}};}
test("payroll unknown seals across remount",async()=>{const registry=new Map(),h=payHarness({registry});h.button().props.onClick();await h.flush();h.unmount();const r=payHarness({registry});assert.equal(r.result(),"unknown");assert.equal(r.button(),undefined);assert.equal(h.calls.length,1);});
test("payroll target is exact",()=>{const h=payHarness({target:"PAID"});h.button().props.onClick();assert.equal(h.calls[0][1],"PAID");});
