import test from "node:test";import assert from "node:assert/strict";import{readFileSync}from"node:fs";import{runInNewContext}from"node:vm";import{setImmediate as tick}from"node:timers/promises";import ts from"typescript";
function load(path,mocks={},globals={}){const code=ts.transpileModule(readFileSync(path,"utf8"),{fileName:path,compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,jsx:ts.JsxEmit.ReactJSX}}).outputText;const module={exports:{}};runInNewContext(code,{module,exports:module.exports,require(name){if(Object.hasOwn(mocks,name))return mocks[name];throw new Error("Unexpected import "+name);},AbortController,Event,...globals},{filename:path});return module.exports;}
const adapter=load("lib/action-center-time-control.ts"),plain=v=>JSON.parse(JSON.stringify(v)),item=(changes={})=>({id:"time:t1",kind:"time-attendance",title:"QA time",subtitle:"QA",module:"time-attendance",href:"/module/time-attendance?entry=t1",subjectType:"Employment",subjectId:"e1",status:"SUBMITTED",createdAt:"2026-10-06T08:00:00.000Z",dueAt:null,urgency:"normal",action:{type:"approve-time",entryId:"t1"},secondaryAction:{type:"reject-time",entryId:"t1"},...changes});
for(const[name,changes,allowed]of[["paired",{},["APPROVED","REJECTED"]],["approval only",{secondaryAction:null},["APPROVED"]],["rejection only",{action:null},["REJECTED"]]])test("adapter "+name,()=>assert.deepEqual(plain(adapter.actionCenterTimeControl(item(changes))),{entryId:"t1",allowedDecisions:allowed}));
for(const candidate of[null,[],{},item({action:null,secondaryAction:null}),item({secondaryAction:{type:"reject-time",entryId:"t2"}}),item({kind:"leave"}),item({action:{type:"approve-leave",requestId:"t1"}})])test("adapter fails closed",()=>assert.equal(adapter.actionCenterTimeControl(candidate),null));
for(const candidate of[item(),item({kind:"leave"}),item({kind:"payroll",action:null}),item({action:null,secondaryAction:null})])test("time metadata cannot fall into generic writes",()=>assert.equal(adapter.isActionCenterTimeItem(candidate),true));
const jsx=(type,props,key)=>({type,props:props||{},key}),descend=n=>!n||typeof n!=="object"?[]:Array.isArray(n)?n.flatMap(descend):[n,...descend(n.props?.children)];
function harness({registry=new Map(),entryId="t1",allowedDecisions,disabled=false,locale="en",confirm=true,submit=async()=>({outcome:"unknown"})}={}){const state=[],refs=[],cleanups=[],calls=[],acks=[];let si=0,ri=0,initial=true,tree,reloads=0;const mod=load("components/time-decision-buttons.tsx",{react:{useState(v){const i=si++;if(initial)state[i]=typeof v==="function"?v():v;return[state[i],v=>{state[i]=typeof v==="function"?v(state[i]):v;}]},useRef(v){const i=ri++;if(initial)refs[i]={current:v};return refs[i]},useEffect(fn){if(initial)cleanups.push(fn());}},"react/jsx-runtime":{jsx,jsxs:jsx},"next/navigation":{useRouter:()=>({refresh(){}})},"lucide-react":{Check:"check",X:"x"},"@/components/locale-provider":{useLocale:()=>({locale})},"@/lib/time-client-action":{async submitTimeAction(...args){calls.push(args);return submit(...args)},async acknowledgeTimeNotification(id){acks.push(id);return true},timeActionMessage(result){return result.outcome;}}},{window:{confirm:()=>confirm,dispatchEvent(){},location:{reload(){reloads++;}}}});const wrapper=mod.TimeDecisionButtons({entryId,allowedDecisions,attemptRegistry:registry,disabled});const render=()=>{si=ri=0;tree=wrapper.type(wrapper.props);initial=false;return tree};render();return{nodes:()=>descend(tree),calls,acks,registry,button:d=>descend(tree).find(n=>n.props["data-time-decision"]===d),result:()=>descend(tree).find(n=>n.props["data-time-decision-result"])?.props["data-time-decision-result"],async flush(){await tick();render()},unmount(){cleanups.forEach(fn=>fn?.())},get reloads(){return reloads;}};}
for(const locale of["en","tr"])for(const outcome of[{outcome:"unknown"},{outcome:"rejected",status:409},{outcome:"saved",id:"t1",status:"APPROVED"}])test(locale+" "+outcome.outcome+" persists across remount",async()=>{const registry=new Map(),h=harness({locale,registry,submit:async()=>outcome});h.button("APPROVED").props.onClick();await h.flush();h.unmount();const returned=harness({locale,registry});assert.equal(returned.result(),outcome.outcome);assert.equal(returned.button("APPROVED"),undefined);assert.equal(returned.button("REJECTED"),undefined);assert.equal(h.calls.length,1);});
test("row seals before request and abort stays unknown",async()=>{let resolve;const registry=new Map(),h=harness({registry,submit:()=>new Promise(r=>{resolve=r})});h.button("APPROVED").props.onClick();h.button("REJECTED").props.onClick();assert.equal(h.calls.length,1);assert.equal(registry.get("t1").outcome,"unknown");h.unmount();assert.equal(h.calls[0][1].signal.aborted,true);resolve({outcome:"saved",id:"t1",status:"APPROVED"});await h.flush();assert.equal(registry.get("t1").outcome,"unknown");assert.equal(h.acks.length,0);});
test("confirmation, disabled and one-sided authority fail closed",()=>{const a=harness({confirm:false});a.button("APPROVED").props.onClick();assert.equal(a.calls.length,0);const b=harness({disabled:true});b.button("APPROVED").props.onClick();assert.equal(b.calls.length,0);const c=harness({allowedDecisions:["APPROVED"]});assert.equal(c.button("REJECTED"),undefined);});
test("registry blocks duplicate representations",()=>{const registry=new Map(),a=harness({registry}),b=harness({registry});a.button("APPROVED").props.onClick();b.button("REJECTED").props.onClick();assert.equal(a.calls.length,1);assert.equal(b.calls.length,0);});
test("reload does not replay",()=>{const h=harness({registry:new Map([["t1",{outcome:"unknown"}]])});const b=h.nodes().find(n=>Object.hasOwn(n.props,"data-time-decision-reload"));b.props.onClick();b.props.onClick();assert.equal(h.reloads,1);assert.equal(h.calls.length,0);});
test("Action Center delegates time and generic handlers exclude it",()=>{const source=readFileSync("components/workflow-action-center.tsx","utf8");assert.match(source,/actionCenterTimeControl\(item\)[\s\S]*<TimeDecisionButtons[\s\S]*attemptRegistry=\{timeAttempts\.current\}/);for(const name of["executeQuickAction","executeSecondaryAction"]){const fn=source.slice(source.indexOf("async function "+name));assert.match(fn.slice(0,fn.indexOf("const copy")),/isActionCenterTimeItem\(item\)/);}assert.ok(!source.includes("/api/time/entries/"));});