import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync, readdirSync } from 'node:fs';
import { createRequire } from 'node:module';
import { randomBytes, scryptSync } from 'node:crypto';
import ts from 'typescript';
const require=createRequire(import.meta.url);
function load(path,mocks={}){const source=readFileSync(path,'utf8');const result=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022},reportDiagnostics:true});assert.equal(result.diagnostics?.filter(x=>x.category===ts.DiagnosticCategory.Error).length,0,path);const m={exports:{}};new Function('require','module','exports',result.outputText)(name=>name in mocks?mocks[name]:require(name),m,m.exports);return m.exports;}
const {sanitizeReturnTo}=load('lib/safe-redirect.ts');
const runtime={runtimeString:()=> 'x'.repeat(48),runtimeNumber:(_n,f)=>f};
const auth=load('lib/auth-session.ts',{'@prisma/client':{PlatformRole:{EMPLOYEE:'EMPLOYEE',TENANT_ADMIN:'TENANT_ADMIN'}},'@/lib/runtime-env':runtime,'@/lib/safe-redirect':{sanitizeReturnTo}});
const input=load('lib/input-validation.ts');
for(const value of ['/a/..//evil.invalid','/%2e//evil.invalid','/a/%2e%2e//evil.invalid','//evil.invalid','/\\evil.invalid','/%5cevil.invalid','/%2fevil.invalid','/%252fevil.invalid','/\nevil.invalid','https://evil.invalid','javascript:alert(1)','/%00x','/%','/%25252525252fevil.invalid',null,{},''])test('redirect rejects '+JSON.stringify(value),()=>{assert.equal(sanitizeReturnTo(value),'/');assert.equal(new URL(sanitizeReturnTo(value),'https://hrbp.invalid').origin,'https://hrbp.invalid');});
for(const value of ['/','/module/people','/module/people?query=Ay%C5%9Fe#record','/auth/sign-in?returnTo=%2Fmodule%2Fpeople'])test('redirect preserves '+value,()=>assert.equal(sanitizeReturnTo(value),value));
test('unsafe fallback cannot escape origin',()=>assert.equal(sanitizeReturnTo(null,'https://evil.invalid'),'/'));
test('malformed unrelated cookie does not destroy valid session cookie',()=>{const x=auth.parseCookies('other=%ZZ; hrbp_session=abc.def');assert.equal(x.hrbp_session,'abc.def');assert.equal(x.other,undefined);});
test('malformed session and duplicate names fail closed',()=>{assert.equal(auth.parseCookies('hrbp_session=%ZZ').hrbp_session,undefined);assert.equal(auth.parseCookies('hrbp_session=a; hrbp_session=b; hrbp_session=c').hrbp_session,undefined);});
test('cookie names do not modify object prototypes',()=>assert.equal(Object.getPrototypeOf(auth.parseCookies('__proto__=value')),null));
const now=Math.floor(Date.now()/1000);const claims={v:2,authMethod:'local',credentialVersion:null,accountSessionVersion:1,tenantSessionVersion:1,tenantId:'t',actorId:'a',subject:'a',role:'EMPLOYEE',displayName:'Test',email:'test@example.invalid',issuedAt:now,exp:now+3600};
for(const value of [{}, {exp:0},{exp:now-1},{exp:'9999999999'},[],null])test('signed payload rejects invalid lifetime '+JSON.stringify(value),()=>{const token=auth.encodeSignedPayload(value,'secret');assert.equal(auth.decodeSignedPayload(token,'secret'),null);});
test('tamper and trailing signature segments rejected',()=>{const token=auth.encodeSignedPayload(claims,'secret');assert.deepEqual(auth.decodeSignedPayload(token,'secret'),claims);assert.equal(auth.decodeSignedPayload(token+'.extra','secret'),null);assert.equal(auth.decodeSignedPayload(token,'wrong'),null);});
for(const raw of ['{','null','[]','true','"string"',''])test('JSON object reader rejects '+JSON.stringify(raw),async()=>assert.equal(await input.readJsonObject(new Request('https://test',{method:'POST',headers:{'content-type':'application/json'},body:raw})),null));
test('bounded JSON reader accepts object and UTF8',async()=>assert.deepEqual(await input.readJsonObject(new Request('https://test',{method:'POST',headers:{'content-type':'application/json'},body:'{"name":"Ayşe"}'})),{name:'Ayşe'}));
test('oversized, invalid UTF8 and incorrect content type rejected',async()=>{for(const body of ['{"text":"'+'a'.repeat(66000)+'"}',new Uint8Array([0xc3,0x28])])assert.equal(await input.readJsonObject(new Request('https://test',{method:'POST',headers:{'content-type':'application/json'},body})),null);assert.equal(await input.readJsonObject(new Request('https://test',{method:'POST',headers:{'content-type':'text/plain'},body:'{}'})),null);});
function verifier(user,employment={id:'e'},sessionMaxMinutes=480){const calls=[];const db={userAccount:{findFirst:async args=>{calls.push(args);if(user instanceof Error)throw user;return user?.active===false?null:user;}},tenantSecurityPolicy:{findUnique:async()=>({sessionMaxMinutes})},employment:{findFirst:async()=>employment}};return {...load('lib/verified-session.ts',{'@/lib/auth-session':auth,'@/lib/db':{db}}),calls};}
const user={id:'a',subject:'a',role:'EMPLOYEE',email:'test@example.invalid',localAuthEnabled:true,localPasswordUpdatedAt:null,sessionVersion:1,tenant:{sessionVersion:1}};
test('active identity verified on every invocation without shared caching',async()=>{const v=verifier({...user});assert.deepEqual(await v.verifySessionAccount(claims),claims);assert.deepEqual(await v.verifySessionAccount(claims),claims);assert.equal(v.calls.length,2);assert.deepEqual(v.calls[0].where,{id:'a',tenantId:'t',active:true});});
for(const [kind,change]of Object.entries({disabled:{active:false},role:{role:'TENANT_ADMIN'},subject:{subject:'changed'},email:{email:'other'},localDisabled:{localAuthEnabled:false},passwordReset:{localPasswordUpdatedAt:new Date()},accountRevoked:{sessionVersion:2},tenantRevoked:{tenant:{sessionVersion:2}}}))test('account change rejects old session: '+kind,async()=>assert.equal(await verifier({...user,...change}).verifySessionAccount(claims),null));
test('new versioned local cookie accepted after password reset',async()=>{const date=new Date();assert.ok(await verifier({...user,localPasswordUpdatedAt:date}).verifySessionAccount({...claims,credentialVersion:date.toISOString()}));});
test('OIDC does not depend on local password availability',async()=>assert.ok(await verifier({...user,localAuthEnabled:false}).verifySessionAccount({...claims,authMethod:'oidc'})));
test('tenant session policy narrows existing session lifetime immediately',async()=>assert.equal(await verifier(user,{id:'e'},15).verifySessionAccount({...claims,issuedAt:now-16*60,exp:now+3600}),null));
test('legacy v1 signed session requires reauthentication',async()=>assert.equal(auth.validSessionClaims({...claims,v:1}),false));
test('session lifetime uses the tighter platform or tenant limit',()=>{assert.equal(auth.effectiveSessionMaxMinutes(30),30);assert.equal(auth.effectiveSessionMaxMinutes(1200),480);});
test('legacy untyped session requires reauthentication',async()=>assert.equal(await verifier(user).verifySessionAccount({...claims,authMethod:undefined}),null));
test('unavailable database and terminated employment fail closed',async()=>{assert.equal(await verifier(new Error('offline')).verifySessionAccount(claims),null);assert.equal(await verifier(user,null).verifySessionAccount({...claims,employmentId:'e'}),null);});
const local=load('lib/local-auth.ts');
test('legacy seed hash can authenticate and canonical hashes round-trip',()=>{const password='temporary-test-password';const salt=randomBytes(16).toString('base64url'),digest=scryptSync(password,Buffer.from(salt,'base64url'),64,{N:16384,r:8,p:1,maxmem:64*1024*1024}).toString('base64url');const legacy=`scrypt$16384$8$1${salt}${digest}`;assert.ok(local.isLegacySeedPasswordHash(legacy));assert.ok(local.verifyLocalPassword(password,legacy));assert.equal(local.verifyLocalPassword('wrong-test-password',legacy),false);const fixed=local.hashLocalPassword(password);assert.equal(fixed.split('$').length,6);assert.ok(local.verifyLocalPassword(password,fixed));assert.equal(local.verifyLocalPassword(password,legacy+'x'),false);});
const logout=load('app/api/auth/logout/route.ts',{'@/lib/auth-session':auth,'@/lib/request-context':{mutationOriginAllowed:r=>r.headers.get('origin')===new URL(r.url).origin}});
test('GET and prefetch logout cannot erase cookies',async()=>{const r=await logout.GET(new Request('https://hrbp.invalid/api/auth/logout',{headers:{'next-router-prefetch':'1'}}));assert.equal(r.status,405);assert.equal(r.headers.get('set-cookie'),null);});
test('explicit same-origin POST logout clears cookie and redirects',async()=>{const r=await logout.POST(new Request('https://hrbp.invalid/api/auth/logout',{method:'POST',headers:{origin:'https://hrbp.invalid'}}));assert.equal(r.status,303);assert.match(r.headers.get('set-cookie'),/Max-Age=0/);});
for(const origin of [null,'https://evil.invalid'])test('untrusted logout blocked '+origin,async()=>{const r=await logout.POST(new Request('https://hrbp.invalid/api/auth/logout',{method:'POST',headers:origin?{origin}:{}}));assert.equal(r.status,403);assert.equal(r.headers.get('set-cookie'),null);});
function files(dir){return readdirSync(dir,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(dir+'/'+e.name):[dir+'/'+e.name]);}
test('all context consumers await current-account verification',()=>{let calls=0;for(const f of [...files('app'),...files('lib')].filter(f=>/\.tsx?$/.test(f))){const source=readFileSync(f,'utf8'),sf=ts.createSourceFile(f,source,ts.ScriptTarget.Latest,true);function visit(n){if(ts.isCallExpression(n)&&n.expression.getText(sf)==='getRequestContext'){assert.ok(ts.isAwaitExpression(n.parent),'Unawaited account check: '+f);calls++;}ts.forEachChild(n,visit);}visit(sf);}assert.ok(calls>=177);});
test('signout renderers use explicit POST forms, never Next links',()=>{for(const f of ['components/session-indicator.tsx','components/topbar-account.tsx']){const text=readFileSync(f,'utf8');assert.match(text,/<form action="\/api\/auth\/logout" method="post"/);assert.doesNotMatch(text,/href="\/api\/auth\/logout"/);}});
test('source has no unbounded direct request.json in API handlers',()=>{for(const f of files('app/api').filter(f=>f.endsWith('.ts')))assert.doesNotMatch(readFileSync(f,'utf8'),/request\.json\(/,f);});

test('helper context types unwrap asynchronous account verification',()=>{for(const f of files('app').filter(f=>f.endsWith('.ts')))assert.doesNotMatch(readFileSync(f,'utf8'),/NonNullable<ReturnType<typeof getRequestContext>>/,f);});
